// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: elandnode/reg/v1/tx.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "elandnode.reg.v1";

export interface MsgRegisterLandRegistry {
  registryId: string;
  district: string;
  location: string;
  contact: string;
  creator: string;
}

export interface MsgRegisterLandRegistryResponse {
  status: string;
  code: number;
  message: string;
  data: string;
  requestId: string;
  timestamp: string;
}

function createBaseMsgRegisterLandRegistry(): MsgRegisterLandRegistry {
  return { registryId: "", district: "", location: "", contact: "", creator: "" };
}

export const MsgRegisterLandRegistry: MessageFns<MsgRegisterLandRegistry> = {
  encode(message: MsgRegisterLandRegistry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.registryId !== "") {
      writer.uint32(10).string(message.registryId);
    }
    if (message.district !== "") {
      writer.uint32(18).string(message.district);
    }
    if (message.location !== "") {
      writer.uint32(26).string(message.location);
    }
    if (message.contact !== "") {
      writer.uint32(34).string(message.contact);
    }
    if (message.creator !== "") {
      writer.uint32(42).string(message.creator);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRegisterLandRegistry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgRegisterLandRegistry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.registryId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.district = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.location = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.contact = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgRegisterLandRegistry {
    return {
      registryId: isSet(object.registryId) ? globalThis.String(object.registryId) : "",
      district: isSet(object.district) ? globalThis.String(object.district) : "",
      location: isSet(object.location) ? globalThis.String(object.location) : "",
      contact: isSet(object.contact) ? globalThis.String(object.contact) : "",
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
    };
  },

  toJSON(message: MsgRegisterLandRegistry): unknown {
    const obj: any = {};
    if (message.registryId !== "") {
      obj.registryId = message.registryId;
    }
    if (message.district !== "") {
      obj.district = message.district;
    }
    if (message.location !== "") {
      obj.location = message.location;
    }
    if (message.contact !== "") {
      obj.contact = message.contact;
    }
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRegisterLandRegistry>, I>>(base?: I): MsgRegisterLandRegistry {
    return MsgRegisterLandRegistry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRegisterLandRegistry>, I>>(object: I): MsgRegisterLandRegistry {
    const message = createBaseMsgRegisterLandRegistry();
    message.registryId = object.registryId ?? "";
    message.district = object.district ?? "";
    message.location = object.location ?? "";
    message.contact = object.contact ?? "";
    message.creator = object.creator ?? "";
    return message;
  },
};

function createBaseMsgRegisterLandRegistryResponse(): MsgRegisterLandRegistryResponse {
  return { status: "", code: 0, message: "", data: "", requestId: "", timestamp: "" };
}

export const MsgRegisterLandRegistryResponse: MessageFns<MsgRegisterLandRegistryResponse> = {
  encode(message: MsgRegisterLandRegistryResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.code !== 0) {
      writer.uint32(16).int32(message.code);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    if (message.data !== "") {
      writer.uint32(34).string(message.data);
    }
    if (message.requestId !== "") {
      writer.uint32(42).string(message.requestId);
    }
    if (message.timestamp !== "") {
      writer.uint32(50).string(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRegisterLandRegistryResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgRegisterLandRegistryResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.code = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.data = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgRegisterLandRegistryResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      data: isSet(object.data) ? globalThis.String(object.data) : "",
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
    };
  },

  toJSON(message: MsgRegisterLandRegistryResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.data !== "") {
      obj.data = message.data;
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.timestamp !== "") {
      obj.timestamp = message.timestamp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRegisterLandRegistryResponse>, I>>(base?: I): MsgRegisterLandRegistryResponse {
    return MsgRegisterLandRegistryResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRegisterLandRegistryResponse>, I>>(
    object: I,
  ): MsgRegisterLandRegistryResponse {
    const message = createBaseMsgRegisterLandRegistryResponse();
    message.status = object.status ?? "";
    message.code = object.code ?? 0;
    message.message = object.message ?? "";
    message.data = object.data ?? "";
    message.requestId = object.requestId ?? "";
    message.timestamp = object.timestamp ?? "";
    return message;
  },
};

/** Msg defines the Msg service. */
export interface Msg {
  /**
   * RegisterLandRegistry allows an administrator to create a new Land Registry Office
   * on-chain. This message records key information such as the registry’s ID,
   * district, location, and contact details. Once registered, the office becomes
   * an authorized entity that can manage notaries, approve deeds, and oversee
   * folio and parcel operations within its jurisdiction.
   */
  RegisterLandRegistry(request: MsgRegisterLandRegistry): Promise<MsgRegisterLandRegistryResponse>;
}

export const MsgServiceName = "elandnode.reg.v1.Msg";
export class MsgClientImpl implements Msg {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || MsgServiceName;
    this.rpc = rpc;
    this.RegisterLandRegistry = this.RegisterLandRegistry.bind(this);
  }
  RegisterLandRegistry(request: MsgRegisterLandRegistry): Promise<MsgRegisterLandRegistryResponse> {
    const data = MsgRegisterLandRegistry.encode(request).finish();
    const promise = this.rpc.request(this.service, "RegisterLandRegistry", data);
    return promise.then((data) => MsgRegisterLandRegistryResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
