// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: elandnode/parcel/v1/parcel.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "elandnode.parcel.v1";

export interface LandParcel {
  parcelId: string;
  district: string;
  extent: string;
  planCid: string;
  surveyDeptRef: string;
  registryId: string;
  approved: boolean;
}

function createBaseLandParcel(): LandParcel {
  return { parcelId: "", district: "", extent: "", planCid: "", surveyDeptRef: "", registryId: "", approved: false };
}

export const LandParcel: MessageFns<LandParcel> = {
  encode(message: LandParcel, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.parcelId !== "") {
      writer.uint32(10).string(message.parcelId);
    }
    if (message.district !== "") {
      writer.uint32(18).string(message.district);
    }
    if (message.extent !== "") {
      writer.uint32(26).string(message.extent);
    }
    if (message.planCid !== "") {
      writer.uint32(34).string(message.planCid);
    }
    if (message.surveyDeptRef !== "") {
      writer.uint32(42).string(message.surveyDeptRef);
    }
    if (message.registryId !== "") {
      writer.uint32(50).string(message.registryId);
    }
    if (message.approved !== false) {
      writer.uint32(56).bool(message.approved);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LandParcel {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLandParcel();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.parcelId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.district = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.extent = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.planCid = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.surveyDeptRef = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.registryId = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.approved = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LandParcel {
    return {
      parcelId: isSet(object.parcelId) ? globalThis.String(object.parcelId) : "",
      district: isSet(object.district) ? globalThis.String(object.district) : "",
      extent: isSet(object.extent) ? globalThis.String(object.extent) : "",
      planCid: isSet(object.planCid) ? globalThis.String(object.planCid) : "",
      surveyDeptRef: isSet(object.surveyDeptRef) ? globalThis.String(object.surveyDeptRef) : "",
      registryId: isSet(object.registryId) ? globalThis.String(object.registryId) : "",
      approved: isSet(object.approved) ? globalThis.Boolean(object.approved) : false,
    };
  },

  toJSON(message: LandParcel): unknown {
    const obj: any = {};
    if (message.parcelId !== "") {
      obj.parcelId = message.parcelId;
    }
    if (message.district !== "") {
      obj.district = message.district;
    }
    if (message.extent !== "") {
      obj.extent = message.extent;
    }
    if (message.planCid !== "") {
      obj.planCid = message.planCid;
    }
    if (message.surveyDeptRef !== "") {
      obj.surveyDeptRef = message.surveyDeptRef;
    }
    if (message.registryId !== "") {
      obj.registryId = message.registryId;
    }
    if (message.approved !== false) {
      obj.approved = message.approved;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LandParcel>, I>>(base?: I): LandParcel {
    return LandParcel.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LandParcel>, I>>(object: I): LandParcel {
    const message = createBaseLandParcel();
    message.parcelId = object.parcelId ?? "";
    message.district = object.district ?? "";
    message.extent = object.extent ?? "";
    message.planCid = object.planCid ?? "";
    message.surveyDeptRef = object.surveyDeptRef ?? "";
    message.registryId = object.registryId ?? "";
    message.approved = object.approved ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
