// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: elandnode/parcel/v1/tx.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "elandnode.parcel.v1";

export interface MsgVerifyParcel {
  parcelId: string;
  registryId: string;
  approved: boolean;
  creator: string;
}

export interface MsgVerifyParcelResponse {
  status: string;
  code: number;
  message: string;
  data: string;
  requestId: string;
  timestamp: string;
}

export interface MsgRegisterParcel {
  registrar: string;
  parcelId: string;
  district: string;
  extent: string;
  planCid: string;
  surveyDeptRef: string;
  registryId: string;
  creator: string;
}

export interface MsgRegisterParcelResponse {
  status: string;
  code: number;
  message: string;
  data: string;
  requestId: string;
  timestamp: string;
}

function createBaseMsgVerifyParcel(): MsgVerifyParcel {
  return { parcelId: "", registryId: "", approved: false, creator: "" };
}

export const MsgVerifyParcel: MessageFns<MsgVerifyParcel> = {
  encode(message: MsgVerifyParcel, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.parcelId !== "") {
      writer.uint32(10).string(message.parcelId);
    }
    if (message.registryId !== "") {
      writer.uint32(18).string(message.registryId);
    }
    if (message.approved !== false) {
      writer.uint32(24).bool(message.approved);
    }
    if (message.creator !== "") {
      writer.uint32(34).string(message.creator);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgVerifyParcel {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgVerifyParcel();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.parcelId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.registryId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.approved = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgVerifyParcel {
    return {
      parcelId: isSet(object.parcelId) ? globalThis.String(object.parcelId) : "",
      registryId: isSet(object.registryId) ? globalThis.String(object.registryId) : "",
      approved: isSet(object.approved) ? globalThis.Boolean(object.approved) : false,
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
    };
  },

  toJSON(message: MsgVerifyParcel): unknown {
    const obj: any = {};
    if (message.parcelId !== "") {
      obj.parcelId = message.parcelId;
    }
    if (message.registryId !== "") {
      obj.registryId = message.registryId;
    }
    if (message.approved !== false) {
      obj.approved = message.approved;
    }
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgVerifyParcel>, I>>(base?: I): MsgVerifyParcel {
    return MsgVerifyParcel.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgVerifyParcel>, I>>(object: I): MsgVerifyParcel {
    const message = createBaseMsgVerifyParcel();
    message.parcelId = object.parcelId ?? "";
    message.registryId = object.registryId ?? "";
    message.approved = object.approved ?? false;
    message.creator = object.creator ?? "";
    return message;
  },
};

function createBaseMsgVerifyParcelResponse(): MsgVerifyParcelResponse {
  return { status: "", code: 0, message: "", data: "", requestId: "", timestamp: "" };
}

export const MsgVerifyParcelResponse: MessageFns<MsgVerifyParcelResponse> = {
  encode(message: MsgVerifyParcelResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.code !== 0) {
      writer.uint32(16).int32(message.code);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    if (message.data !== "") {
      writer.uint32(34).string(message.data);
    }
    if (message.requestId !== "") {
      writer.uint32(42).string(message.requestId);
    }
    if (message.timestamp !== "") {
      writer.uint32(50).string(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgVerifyParcelResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgVerifyParcelResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.code = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.data = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgVerifyParcelResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      data: isSet(object.data) ? globalThis.String(object.data) : "",
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
    };
  },

  toJSON(message: MsgVerifyParcelResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.data !== "") {
      obj.data = message.data;
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.timestamp !== "") {
      obj.timestamp = message.timestamp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgVerifyParcelResponse>, I>>(base?: I): MsgVerifyParcelResponse {
    return MsgVerifyParcelResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgVerifyParcelResponse>, I>>(object: I): MsgVerifyParcelResponse {
    const message = createBaseMsgVerifyParcelResponse();
    message.status = object.status ?? "";
    message.code = object.code ?? 0;
    message.message = object.message ?? "";
    message.data = object.data ?? "";
    message.requestId = object.requestId ?? "";
    message.timestamp = object.timestamp ?? "";
    return message;
  },
};

function createBaseMsgRegisterParcel(): MsgRegisterParcel {
  return {
    registrar: "",
    parcelId: "",
    district: "",
    extent: "",
    planCid: "",
    surveyDeptRef: "",
    registryId: "",
    creator: "",
  };
}

export const MsgRegisterParcel: MessageFns<MsgRegisterParcel> = {
  encode(message: MsgRegisterParcel, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.registrar !== "") {
      writer.uint32(10).string(message.registrar);
    }
    if (message.parcelId !== "") {
      writer.uint32(18).string(message.parcelId);
    }
    if (message.district !== "") {
      writer.uint32(26).string(message.district);
    }
    if (message.extent !== "") {
      writer.uint32(34).string(message.extent);
    }
    if (message.planCid !== "") {
      writer.uint32(42).string(message.planCid);
    }
    if (message.surveyDeptRef !== "") {
      writer.uint32(50).string(message.surveyDeptRef);
    }
    if (message.registryId !== "") {
      writer.uint32(58).string(message.registryId);
    }
    if (message.creator !== "") {
      writer.uint32(66).string(message.creator);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRegisterParcel {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgRegisterParcel();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.registrar = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.parcelId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.district = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.extent = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.planCid = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.surveyDeptRef = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.registryId = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgRegisterParcel {
    return {
      registrar: isSet(object.registrar) ? globalThis.String(object.registrar) : "",
      parcelId: isSet(object.parcelId) ? globalThis.String(object.parcelId) : "",
      district: isSet(object.district) ? globalThis.String(object.district) : "",
      extent: isSet(object.extent) ? globalThis.String(object.extent) : "",
      planCid: isSet(object.planCid) ? globalThis.String(object.planCid) : "",
      surveyDeptRef: isSet(object.surveyDeptRef) ? globalThis.String(object.surveyDeptRef) : "",
      registryId: isSet(object.registryId) ? globalThis.String(object.registryId) : "",
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
    };
  },

  toJSON(message: MsgRegisterParcel): unknown {
    const obj: any = {};
    if (message.registrar !== "") {
      obj.registrar = message.registrar;
    }
    if (message.parcelId !== "") {
      obj.parcelId = message.parcelId;
    }
    if (message.district !== "") {
      obj.district = message.district;
    }
    if (message.extent !== "") {
      obj.extent = message.extent;
    }
    if (message.planCid !== "") {
      obj.planCid = message.planCid;
    }
    if (message.surveyDeptRef !== "") {
      obj.surveyDeptRef = message.surveyDeptRef;
    }
    if (message.registryId !== "") {
      obj.registryId = message.registryId;
    }
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRegisterParcel>, I>>(base?: I): MsgRegisterParcel {
    return MsgRegisterParcel.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRegisterParcel>, I>>(object: I): MsgRegisterParcel {
    const message = createBaseMsgRegisterParcel();
    message.registrar = object.registrar ?? "";
    message.parcelId = object.parcelId ?? "";
    message.district = object.district ?? "";
    message.extent = object.extent ?? "";
    message.planCid = object.planCid ?? "";
    message.surveyDeptRef = object.surveyDeptRef ?? "";
    message.registryId = object.registryId ?? "";
    message.creator = object.creator ?? "";
    return message;
  },
};

function createBaseMsgRegisterParcelResponse(): MsgRegisterParcelResponse {
  return { status: "", code: 0, message: "", data: "", requestId: "", timestamp: "" };
}

export const MsgRegisterParcelResponse: MessageFns<MsgRegisterParcelResponse> = {
  encode(message: MsgRegisterParcelResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.code !== 0) {
      writer.uint32(16).int32(message.code);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    if (message.data !== "") {
      writer.uint32(34).string(message.data);
    }
    if (message.requestId !== "") {
      writer.uint32(42).string(message.requestId);
    }
    if (message.timestamp !== "") {
      writer.uint32(50).string(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRegisterParcelResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgRegisterParcelResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.code = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.data = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgRegisterParcelResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      data: isSet(object.data) ? globalThis.String(object.data) : "",
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
    };
  },

  toJSON(message: MsgRegisterParcelResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.data !== "") {
      obj.data = message.data;
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.timestamp !== "") {
      obj.timestamp = message.timestamp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRegisterParcelResponse>, I>>(base?: I): MsgRegisterParcelResponse {
    return MsgRegisterParcelResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRegisterParcelResponse>, I>>(object: I): MsgRegisterParcelResponse {
    const message = createBaseMsgRegisterParcelResponse();
    message.status = object.status ?? "";
    message.code = object.code ?? 0;
    message.message = object.message ?? "";
    message.data = object.data ?? "";
    message.requestId = object.requestId ?? "";
    message.timestamp = object.timestamp ?? "";
    return message;
  },
};

/** Msg defines the Msg service. */
export interface Msg {
  /**
   * RegisterParcel allows a Land Registry Officer to register a new land parcel
   * on-chain after it has been surveyed and verified. This message records
   * key parcel details such as parcel ID, district, extent, and survey plan reference,
   * linking it to the corresponding registry and survey department records.
   */
  RegisterParcel(request: MsgRegisterParcel): Promise<MsgRegisterParcelResponse>;
  /**
   * VerifyParcel allows a authorized registry officer
   * to verify a previously registered land parcel. Successful verification marks
   * the parcel as officially approved, enabling it to be associated with a folio
   * and included in future land transactions.
   */
  VerifyParcel(request: MsgVerifyParcel): Promise<MsgVerifyParcelResponse>;
}

export const MsgServiceName = "elandnode.parcel.v1.Msg";
export class MsgClientImpl implements Msg {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || MsgServiceName;
    this.rpc = rpc;
    this.RegisterParcel = this.RegisterParcel.bind(this);
    this.VerifyParcel = this.VerifyParcel.bind(this);
  }
  RegisterParcel(request: MsgRegisterParcel): Promise<MsgRegisterParcelResponse> {
    const data = MsgRegisterParcel.encode(request).finish();
    const promise = this.rpc.request(this.service, "RegisterParcel", data);
    return promise.then((data) => MsgRegisterParcelResponse.decode(new BinaryReader(data)));
  }

  VerifyParcel(request: MsgVerifyParcel): Promise<MsgVerifyParcelResponse> {
    const data = MsgVerifyParcel.encode(request).finish();
    const promise = this.rpc.request(this.service, "VerifyParcel", data);
    return promise.then((data) => MsgVerifyParcelResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
