// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: elandnode/owner/v1/genesis.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Owner } from "./owner";
import { Params } from "./params";

export const protobufPackage = "elandnode.owner.v1";

/** Creator index */
export interface CreatorIndexEntry {
  address: string;
}

export interface CreatorToNicIndex {
  creator: string;
  nic: string;
}

/** GenesisState defines the owner module's genesis state. */
export interface GenesisState {
  /** params defines all the parameters of the module. */
  params: Params | undefined;
  ownerList: Owner[];
  /** Creator index for uniqueness */
  creatorIndex: CreatorIndexEntry[];
  /** Creator + did index for uniqueness */
  CreatorToNicNdex: CreatorToNicIndex[];
}

function createBaseCreatorIndexEntry(): CreatorIndexEntry {
  return { address: "" };
}

export const CreatorIndexEntry: MessageFns<CreatorIndexEntry> = {
  encode(message: CreatorIndexEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.address !== "") {
      writer.uint32(10).string(message.address);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreatorIndexEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreatorIndexEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.address = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreatorIndexEntry {
    return { address: isSet(object.address) ? globalThis.String(object.address) : "" };
  },

  toJSON(message: CreatorIndexEntry): unknown {
    const obj: any = {};
    if (message.address !== "") {
      obj.address = message.address;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreatorIndexEntry>, I>>(base?: I): CreatorIndexEntry {
    return CreatorIndexEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreatorIndexEntry>, I>>(object: I): CreatorIndexEntry {
    const message = createBaseCreatorIndexEntry();
    message.address = object.address ?? "";
    return message;
  },
};

function createBaseCreatorToNicIndex(): CreatorToNicIndex {
  return { creator: "", nic: "" };
}

export const CreatorToNicIndex: MessageFns<CreatorToNicIndex> = {
  encode(message: CreatorToNicIndex, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.nic !== "") {
      writer.uint32(18).string(message.nic);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreatorToNicIndex {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreatorToNicIndex();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.nic = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreatorToNicIndex {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      nic: isSet(object.nic) ? globalThis.String(object.nic) : "",
    };
  },

  toJSON(message: CreatorToNicIndex): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.nic !== "") {
      obj.nic = message.nic;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreatorToNicIndex>, I>>(base?: I): CreatorToNicIndex {
    return CreatorToNicIndex.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreatorToNicIndex>, I>>(object: I): CreatorToNicIndex {
    const message = createBaseCreatorToNicIndex();
    message.creator = object.creator ?? "";
    message.nic = object.nic ?? "";
    return message;
  },
};

function createBaseGenesisState(): GenesisState {
  return { params: undefined, ownerList: [], creatorIndex: [], CreatorToNicNdex: [] };
}

export const GenesisState: MessageFns<GenesisState> = {
  encode(message: GenesisState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(10).fork()).join();
    }
    for (const v of message.ownerList) {
      Owner.encode(v!, writer.uint32(18).fork()).join();
    }
    for (const v of message.creatorIndex) {
      CreatorIndexEntry.encode(v!, writer.uint32(26).fork()).join();
    }
    for (const v of message.CreatorToNicNdex) {
      CreatorToNicIndex.encode(v!, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GenesisState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGenesisState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.ownerList.push(Owner.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.creatorIndex.push(CreatorIndexEntry.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.CreatorToNicNdex.push(CreatorToNicIndex.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GenesisState {
    return {
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
      ownerList: globalThis.Array.isArray(object?.ownerList) ? object.ownerList.map((e: any) => Owner.fromJSON(e)) : [],
      creatorIndex: globalThis.Array.isArray(object?.creatorIndex)
        ? object.creatorIndex.map((e: any) => CreatorIndexEntry.fromJSON(e))
        : [],
      CreatorToNicNdex: globalThis.Array.isArray(object?.CreatorToNicNdex)
        ? object.CreatorToNicNdex.map((e: any) => CreatorToNicIndex.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GenesisState): unknown {
    const obj: any = {};
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    if (message.ownerList?.length) {
      obj.ownerList = message.ownerList.map((e) => Owner.toJSON(e));
    }
    if (message.creatorIndex?.length) {
      obj.creatorIndex = message.creatorIndex.map((e) => CreatorIndexEntry.toJSON(e));
    }
    if (message.CreatorToNicNdex?.length) {
      obj.CreatorToNicNdex = message.CreatorToNicNdex.map((e) => CreatorToNicIndex.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GenesisState>, I>>(base?: I): GenesisState {
    return GenesisState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GenesisState>, I>>(object: I): GenesisState {
    const message = createBaseGenesisState();
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    message.ownerList = object.ownerList?.map((e) => Owner.fromPartial(e)) || [];
    message.creatorIndex = object.creatorIndex?.map((e) => CreatorIndexEntry.fromPartial(e)) || [];
    message.CreatorToNicNdex = object.CreatorToNicNdex?.map((e) => CreatorToNicIndex.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
