// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: elandnode/owner/v1/owner.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "elandnode.owner.v1";

export interface Owner {
  ownerId: string;
  nic: string;
  name: string;
  contact: string;
  address: string;
  verified: boolean;
  registeredDate: string;
}

function createBaseOwner(): Owner {
  return { ownerId: "", nic: "", name: "", contact: "", address: "", verified: false, registeredDate: "" };
}

export const Owner: MessageFns<Owner> = {
  encode(message: Owner, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ownerId !== "") {
      writer.uint32(10).string(message.ownerId);
    }
    if (message.nic !== "") {
      writer.uint32(18).string(message.nic);
    }
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    if (message.contact !== "") {
      writer.uint32(34).string(message.contact);
    }
    if (message.address !== "") {
      writer.uint32(42).string(message.address);
    }
    if (message.verified !== false) {
      writer.uint32(48).bool(message.verified);
    }
    if (message.registeredDate !== "") {
      writer.uint32(58).string(message.registeredDate);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Owner {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOwner();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ownerId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.nic = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.contact = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.address = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.verified = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.registeredDate = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Owner {
    return {
      ownerId: isSet(object.ownerId) ? globalThis.String(object.ownerId) : "",
      nic: isSet(object.nic) ? globalThis.String(object.nic) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      contact: isSet(object.contact) ? globalThis.String(object.contact) : "",
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      verified: isSet(object.verified) ? globalThis.Boolean(object.verified) : false,
      registeredDate: isSet(object.registeredDate) ? globalThis.String(object.registeredDate) : "",
    };
  },

  toJSON(message: Owner): unknown {
    const obj: any = {};
    if (message.ownerId !== "") {
      obj.ownerId = message.ownerId;
    }
    if (message.nic !== "") {
      obj.nic = message.nic;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.contact !== "") {
      obj.contact = message.contact;
    }
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (message.verified !== false) {
      obj.verified = message.verified;
    }
    if (message.registeredDate !== "") {
      obj.registeredDate = message.registeredDate;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Owner>, I>>(base?: I): Owner {
    return Owner.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Owner>, I>>(object: I): Owner {
    const message = createBaseOwner();
    message.ownerId = object.ownerId ?? "";
    message.nic = object.nic ?? "";
    message.name = object.name ?? "";
    message.contact = object.contact ?? "";
    message.address = object.address ?? "";
    message.verified = object.verified ?? false;
    message.registeredDate = object.registeredDate ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
