// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: elandnode/notary/v1/genesis.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Notary } from "./notary";
import { Params } from "./params";

export const protobufPackage = "elandnode.notary.v1";

/** GenesisState defines the notary module's genesis state. */
export interface GenesisState {
  /** params defines all the parameters of the module. */
  params: Params | undefined;
  notaryByNic: Notary[];
  /** All registered notaries keyed by license */
  notaryByLicense: Notary[];
  /** Registry → []NotaryIDs mapping */
  notaryByRegistry: RegistryNotaryMapping[];
}

export interface RegistryNotaryMapping {
  registryId: string;
  notaryIds: string[];
}

function createBaseGenesisState(): GenesisState {
  return { params: undefined, notaryByNic: [], notaryByLicense: [], notaryByRegistry: [] };
}

export const GenesisState: MessageFns<GenesisState> = {
  encode(message: GenesisState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(10).fork()).join();
    }
    for (const v of message.notaryByNic) {
      Notary.encode(v!, writer.uint32(18).fork()).join();
    }
    for (const v of message.notaryByLicense) {
      Notary.encode(v!, writer.uint32(26).fork()).join();
    }
    for (const v of message.notaryByRegistry) {
      RegistryNotaryMapping.encode(v!, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GenesisState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGenesisState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.notaryByNic.push(Notary.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.notaryByLicense.push(Notary.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.notaryByRegistry.push(RegistryNotaryMapping.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GenesisState {
    return {
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
      notaryByNic: globalThis.Array.isArray(object?.notaryByNic)
        ? object.notaryByNic.map((e: any) => Notary.fromJSON(e))
        : [],
      notaryByLicense: globalThis.Array.isArray(object?.notaryByLicense)
        ? object.notaryByLicense.map((e: any) => Notary.fromJSON(e))
        : [],
      notaryByRegistry: globalThis.Array.isArray(object?.notaryByRegistry)
        ? object.notaryByRegistry.map((e: any) => RegistryNotaryMapping.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GenesisState): unknown {
    const obj: any = {};
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    if (message.notaryByNic?.length) {
      obj.notaryByNic = message.notaryByNic.map((e) => Notary.toJSON(e));
    }
    if (message.notaryByLicense?.length) {
      obj.notaryByLicense = message.notaryByLicense.map((e) => Notary.toJSON(e));
    }
    if (message.notaryByRegistry?.length) {
      obj.notaryByRegistry = message.notaryByRegistry.map((e) => RegistryNotaryMapping.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GenesisState>, I>>(base?: I): GenesisState {
    return GenesisState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GenesisState>, I>>(object: I): GenesisState {
    const message = createBaseGenesisState();
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    message.notaryByNic = object.notaryByNic?.map((e) => Notary.fromPartial(e)) || [];
    message.notaryByLicense = object.notaryByLicense?.map((e) => Notary.fromPartial(e)) || [];
    message.notaryByRegistry = object.notaryByRegistry?.map((e) => RegistryNotaryMapping.fromPartial(e)) || [];
    return message;
  },
};

function createBaseRegistryNotaryMapping(): RegistryNotaryMapping {
  return { registryId: "", notaryIds: [] };
}

export const RegistryNotaryMapping: MessageFns<RegistryNotaryMapping> = {
  encode(message: RegistryNotaryMapping, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.registryId !== "") {
      writer.uint32(10).string(message.registryId);
    }
    for (const v of message.notaryIds) {
      writer.uint32(18).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RegistryNotaryMapping {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegistryNotaryMapping();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.registryId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.notaryIds.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RegistryNotaryMapping {
    return {
      registryId: isSet(object.registryId) ? globalThis.String(object.registryId) : "",
      notaryIds: globalThis.Array.isArray(object?.notaryIds)
        ? object.notaryIds.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: RegistryNotaryMapping): unknown {
    const obj: any = {};
    if (message.registryId !== "") {
      obj.registryId = message.registryId;
    }
    if (message.notaryIds?.length) {
      obj.notaryIds = message.notaryIds;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RegistryNotaryMapping>, I>>(base?: I): RegistryNotaryMapping {
    return RegistryNotaryMapping.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RegistryNotaryMapping>, I>>(object: I): RegistryNotaryMapping {
    const message = createBaseRegistryNotaryMapping();
    message.registryId = object.registryId ?? "";
    message.notaryIds = object.notaryIds?.map((e) => e) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
