// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: elandnode/notary/v1/notary.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "elandnode.notary.v1";

export interface Notary {
  notaryId: string;
  name: string;
  licenseNumber: string;
  district: string;
  nic: string;
  verified: boolean;
  registryId: string;
}

export interface StringArray {
  items: string[];
}

function createBaseNotary(): Notary {
  return { notaryId: "", name: "", licenseNumber: "", district: "", nic: "", verified: false, registryId: "" };
}

export const Notary: MessageFns<Notary> = {
  encode(message: Notary, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.notaryId !== "") {
      writer.uint32(10).string(message.notaryId);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.licenseNumber !== "") {
      writer.uint32(26).string(message.licenseNumber);
    }
    if (message.district !== "") {
      writer.uint32(34).string(message.district);
    }
    if (message.nic !== "") {
      writer.uint32(42).string(message.nic);
    }
    if (message.verified !== false) {
      writer.uint32(48).bool(message.verified);
    }
    if (message.registryId !== "") {
      writer.uint32(58).string(message.registryId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Notary {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNotary();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.notaryId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.licenseNumber = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.district = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.nic = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.verified = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.registryId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Notary {
    return {
      notaryId: isSet(object.notaryId) ? globalThis.String(object.notaryId) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      licenseNumber: isSet(object.licenseNumber) ? globalThis.String(object.licenseNumber) : "",
      district: isSet(object.district) ? globalThis.String(object.district) : "",
      nic: isSet(object.nic) ? globalThis.String(object.nic) : "",
      verified: isSet(object.verified) ? globalThis.Boolean(object.verified) : false,
      registryId: isSet(object.registryId) ? globalThis.String(object.registryId) : "",
    };
  },

  toJSON(message: Notary): unknown {
    const obj: any = {};
    if (message.notaryId !== "") {
      obj.notaryId = message.notaryId;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.licenseNumber !== "") {
      obj.licenseNumber = message.licenseNumber;
    }
    if (message.district !== "") {
      obj.district = message.district;
    }
    if (message.nic !== "") {
      obj.nic = message.nic;
    }
    if (message.verified !== false) {
      obj.verified = message.verified;
    }
    if (message.registryId !== "") {
      obj.registryId = message.registryId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Notary>, I>>(base?: I): Notary {
    return Notary.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Notary>, I>>(object: I): Notary {
    const message = createBaseNotary();
    message.notaryId = object.notaryId ?? "";
    message.name = object.name ?? "";
    message.licenseNumber = object.licenseNumber ?? "";
    message.district = object.district ?? "";
    message.nic = object.nic ?? "";
    message.verified = object.verified ?? false;
    message.registryId = object.registryId ?? "";
    return message;
  },
};

function createBaseStringArray(): StringArray {
  return { items: [] };
}

export const StringArray: MessageFns<StringArray> = {
  encode(message: StringArray, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.items) {
      writer.uint32(10).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StringArray {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStringArray();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.items.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StringArray {
    return { items: globalThis.Array.isArray(object?.items) ? object.items.map((e: any) => globalThis.String(e)) : [] };
  },

  toJSON(message: StringArray): unknown {
    const obj: any = {};
    if (message.items?.length) {
      obj.items = message.items;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StringArray>, I>>(base?: I): StringArray {
    return StringArray.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StringArray>, I>>(object: I): StringArray {
    const message = createBaseStringArray();
    message.items = object.items?.map((e) => e) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
