// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: elandnode/notary/v1/query.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { PageRequest, PageResponse } from "../../../cosmos/base/query/v1beta1/pagination";
import { Notary } from "./notary";
import { Params } from "./params";

export const protobufPackage = "elandnode.notary.v1";

/** QueryParamsRequest is request type for the Query/Params RPC method. */
export interface QueryParamsRequest {
}

/** QueryParamsResponse is response type for the Query/Params RPC method. */
export interface QueryParamsResponse {
  /** params holds all the parameters of this module. */
  params: Params | undefined;
}

/** Request / Response Messages */
export interface QueryNotaryByNICRequest {
  nic: string;
}

export interface QueryNotaryByNICResponse {
  notary: Notary | undefined;
  status: string;
  code: number;
  message: string;
  requestId: string;
  timestamp: string;
}

export interface QueryNotaryByLicenseRequest {
  licenseNumber: string;
}

export interface QueryNotaryByLicenseResponse {
  notary: Notary | undefined;
  status: string;
  code: number;
  message: string;
  requestId: string;
  timestamp: string;
}

export interface QueryNotariesByRegistryRequest {
  registryId: string;
  requester: string;
  pagination: PageRequest | undefined;
}

export interface QueryNotariesByRegistryResponse {
  status: string;
  code: number;
  message: string;
  notaries: Notary[];
  requestId: string;
  timestamp: string;
  pagination: PageResponse | undefined;
}

function createBaseQueryParamsRequest(): QueryParamsRequest {
  return {};
}

export const QueryParamsRequest: MessageFns<QueryParamsRequest> = {
  encode(_: QueryParamsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryParamsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): QueryParamsRequest {
    return {};
  },

  toJSON(_: QueryParamsRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(base?: I): QueryParamsRequest {
    return QueryParamsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(_: I): QueryParamsRequest {
    const message = createBaseQueryParamsRequest();
    return message;
  },
};

function createBaseQueryParamsResponse(): QueryParamsResponse {
  return { params: undefined };
}

export const QueryParamsResponse: MessageFns<QueryParamsResponse> = {
  encode(message: QueryParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryParamsResponse {
    return { params: isSet(object.params) ? Params.fromJSON(object.params) : undefined };
  },

  toJSON(message: QueryParamsResponse): unknown {
    const obj: any = {};
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(base?: I): QueryParamsResponse {
    return QueryParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(object: I): QueryParamsResponse {
    const message = createBaseQueryParamsResponse();
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseQueryNotaryByNICRequest(): QueryNotaryByNICRequest {
  return { nic: "" };
}

export const QueryNotaryByNICRequest: MessageFns<QueryNotaryByNICRequest> = {
  encode(message: QueryNotaryByNICRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.nic !== "") {
      writer.uint32(10).string(message.nic);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryNotaryByNICRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryNotaryByNICRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.nic = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryNotaryByNICRequest {
    return { nic: isSet(object.nic) ? globalThis.String(object.nic) : "" };
  },

  toJSON(message: QueryNotaryByNICRequest): unknown {
    const obj: any = {};
    if (message.nic !== "") {
      obj.nic = message.nic;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryNotaryByNICRequest>, I>>(base?: I): QueryNotaryByNICRequest {
    return QueryNotaryByNICRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryNotaryByNICRequest>, I>>(object: I): QueryNotaryByNICRequest {
    const message = createBaseQueryNotaryByNICRequest();
    message.nic = object.nic ?? "";
    return message;
  },
};

function createBaseQueryNotaryByNICResponse(): QueryNotaryByNICResponse {
  return { notary: undefined, status: "", code: 0, message: "", requestId: "", timestamp: "" };
}

export const QueryNotaryByNICResponse: MessageFns<QueryNotaryByNICResponse> = {
  encode(message: QueryNotaryByNICResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.notary !== undefined) {
      Notary.encode(message.notary, writer.uint32(10).fork()).join();
    }
    if (message.status !== "") {
      writer.uint32(18).string(message.status);
    }
    if (message.code !== 0) {
      writer.uint32(24).uint32(message.code);
    }
    if (message.message !== "") {
      writer.uint32(34).string(message.message);
    }
    if (message.requestId !== "") {
      writer.uint32(42).string(message.requestId);
    }
    if (message.timestamp !== "") {
      writer.uint32(50).string(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryNotaryByNICResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryNotaryByNICResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.notary = Notary.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.code = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryNotaryByNICResponse {
    return {
      notary: isSet(object.notary) ? Notary.fromJSON(object.notary) : undefined,
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
    };
  },

  toJSON(message: QueryNotaryByNICResponse): unknown {
    const obj: any = {};
    if (message.notary !== undefined) {
      obj.notary = Notary.toJSON(message.notary);
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.timestamp !== "") {
      obj.timestamp = message.timestamp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryNotaryByNICResponse>, I>>(base?: I): QueryNotaryByNICResponse {
    return QueryNotaryByNICResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryNotaryByNICResponse>, I>>(object: I): QueryNotaryByNICResponse {
    const message = createBaseQueryNotaryByNICResponse();
    message.notary = (object.notary !== undefined && object.notary !== null)
      ? Notary.fromPartial(object.notary)
      : undefined;
    message.status = object.status ?? "";
    message.code = object.code ?? 0;
    message.message = object.message ?? "";
    message.requestId = object.requestId ?? "";
    message.timestamp = object.timestamp ?? "";
    return message;
  },
};

function createBaseQueryNotaryByLicenseRequest(): QueryNotaryByLicenseRequest {
  return { licenseNumber: "" };
}

export const QueryNotaryByLicenseRequest: MessageFns<QueryNotaryByLicenseRequest> = {
  encode(message: QueryNotaryByLicenseRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.licenseNumber !== "") {
      writer.uint32(10).string(message.licenseNumber);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryNotaryByLicenseRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryNotaryByLicenseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.licenseNumber = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryNotaryByLicenseRequest {
    return { licenseNumber: isSet(object.licenseNumber) ? globalThis.String(object.licenseNumber) : "" };
  },

  toJSON(message: QueryNotaryByLicenseRequest): unknown {
    const obj: any = {};
    if (message.licenseNumber !== "") {
      obj.licenseNumber = message.licenseNumber;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryNotaryByLicenseRequest>, I>>(base?: I): QueryNotaryByLicenseRequest {
    return QueryNotaryByLicenseRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryNotaryByLicenseRequest>, I>>(object: I): QueryNotaryByLicenseRequest {
    const message = createBaseQueryNotaryByLicenseRequest();
    message.licenseNumber = object.licenseNumber ?? "";
    return message;
  },
};

function createBaseQueryNotaryByLicenseResponse(): QueryNotaryByLicenseResponse {
  return { notary: undefined, status: "", code: 0, message: "", requestId: "", timestamp: "" };
}

export const QueryNotaryByLicenseResponse: MessageFns<QueryNotaryByLicenseResponse> = {
  encode(message: QueryNotaryByLicenseResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.notary !== undefined) {
      Notary.encode(message.notary, writer.uint32(10).fork()).join();
    }
    if (message.status !== "") {
      writer.uint32(18).string(message.status);
    }
    if (message.code !== 0) {
      writer.uint32(24).uint32(message.code);
    }
    if (message.message !== "") {
      writer.uint32(34).string(message.message);
    }
    if (message.requestId !== "") {
      writer.uint32(42).string(message.requestId);
    }
    if (message.timestamp !== "") {
      writer.uint32(50).string(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryNotaryByLicenseResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryNotaryByLicenseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.notary = Notary.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.code = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryNotaryByLicenseResponse {
    return {
      notary: isSet(object.notary) ? Notary.fromJSON(object.notary) : undefined,
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
    };
  },

  toJSON(message: QueryNotaryByLicenseResponse): unknown {
    const obj: any = {};
    if (message.notary !== undefined) {
      obj.notary = Notary.toJSON(message.notary);
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.timestamp !== "") {
      obj.timestamp = message.timestamp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryNotaryByLicenseResponse>, I>>(base?: I): QueryNotaryByLicenseResponse {
    return QueryNotaryByLicenseResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryNotaryByLicenseResponse>, I>>(object: I): QueryNotaryByLicenseResponse {
    const message = createBaseQueryNotaryByLicenseResponse();
    message.notary = (object.notary !== undefined && object.notary !== null)
      ? Notary.fromPartial(object.notary)
      : undefined;
    message.status = object.status ?? "";
    message.code = object.code ?? 0;
    message.message = object.message ?? "";
    message.requestId = object.requestId ?? "";
    message.timestamp = object.timestamp ?? "";
    return message;
  },
};

function createBaseQueryNotariesByRegistryRequest(): QueryNotariesByRegistryRequest {
  return { registryId: "", requester: "", pagination: undefined };
}

export const QueryNotariesByRegistryRequest: MessageFns<QueryNotariesByRegistryRequest> = {
  encode(message: QueryNotariesByRegistryRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.registryId !== "") {
      writer.uint32(10).string(message.registryId);
    }
    if (message.requester !== "") {
      writer.uint32(18).string(message.requester);
    }
    if (message.pagination !== undefined) {
      PageRequest.encode(message.pagination, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryNotariesByRegistryRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryNotariesByRegistryRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.registryId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.requester = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.pagination = PageRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryNotariesByRegistryRequest {
    return {
      registryId: isSet(object.registryId) ? globalThis.String(object.registryId) : "",
      requester: isSet(object.requester) ? globalThis.String(object.requester) : "",
      pagination: isSet(object.pagination) ? PageRequest.fromJSON(object.pagination) : undefined,
    };
  },

  toJSON(message: QueryNotariesByRegistryRequest): unknown {
    const obj: any = {};
    if (message.registryId !== "") {
      obj.registryId = message.registryId;
    }
    if (message.requester !== "") {
      obj.requester = message.requester;
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageRequest.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryNotariesByRegistryRequest>, I>>(base?: I): QueryNotariesByRegistryRequest {
    return QueryNotariesByRegistryRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryNotariesByRegistryRequest>, I>>(
    object: I,
  ): QueryNotariesByRegistryRequest {
    const message = createBaseQueryNotariesByRegistryRequest();
    message.registryId = object.registryId ?? "";
    message.requester = object.requester ?? "";
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageRequest.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseQueryNotariesByRegistryResponse(): QueryNotariesByRegistryResponse {
  return { status: "", code: 0, message: "", notaries: [], requestId: "", timestamp: "", pagination: undefined };
}

export const QueryNotariesByRegistryResponse: MessageFns<QueryNotariesByRegistryResponse> = {
  encode(message: QueryNotariesByRegistryResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(18).string(message.status);
    }
    if (message.code !== 0) {
      writer.uint32(24).uint32(message.code);
    }
    if (message.message !== "") {
      writer.uint32(34).string(message.message);
    }
    for (const v of message.notaries) {
      Notary.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.requestId !== "") {
      writer.uint32(42).string(message.requestId);
    }
    if (message.timestamp !== "") {
      writer.uint32(50).string(message.timestamp);
    }
    if (message.pagination !== undefined) {
      PageResponse.encode(message.pagination, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryNotariesByRegistryResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryNotariesByRegistryResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.code = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.notaries.push(Notary.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.pagination = PageResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryNotariesByRegistryResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      notaries: globalThis.Array.isArray(object?.notaries) ? object.notaries.map((e: any) => Notary.fromJSON(e)) : [],
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
      pagination: isSet(object.pagination) ? PageResponse.fromJSON(object.pagination) : undefined,
    };
  },

  toJSON(message: QueryNotariesByRegistryResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.notaries?.length) {
      obj.notaries = message.notaries.map((e) => Notary.toJSON(e));
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.timestamp !== "") {
      obj.timestamp = message.timestamp;
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageResponse.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryNotariesByRegistryResponse>, I>>(base?: I): QueryNotariesByRegistryResponse {
    return QueryNotariesByRegistryResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryNotariesByRegistryResponse>, I>>(
    object: I,
  ): QueryNotariesByRegistryResponse {
    const message = createBaseQueryNotariesByRegistryResponse();
    message.status = object.status ?? "";
    message.code = object.code ?? 0;
    message.message = object.message ?? "";
    message.notaries = object.notaries?.map((e) => Notary.fromPartial(e)) || [];
    message.requestId = object.requestId ?? "";
    message.timestamp = object.timestamp ?? "";
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageResponse.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

/** Query defines the gRPC querier service. */
export interface Query {
  /** Parameters queries the parameters of the module. */
  Params(request: QueryParamsRequest): Promise<QueryParamsResponse>;
  /**
   * NotaryByNIC retrieves the notary's registration details using their NIC number.
   * This query helps verify an individual notary’s identity and credentials
   * based on their national identification number.
   */
  NotaryByNIC(request: QueryNotaryByNICRequest): Promise<QueryNotaryByNICResponse>;
  /**
   * NotaryByLicense retrieves a notary’s record using their official license number.
   * Useful for verifying the license status, district, and associated registry office
   * of a particular notary.
   */
  NotaryByLicense(request: QueryNotaryByLicenseRequest): Promise<QueryNotaryByLicenseResponse>;
  /**
   * NotariesByRegistry lists all notaries who are registered under a specific
   * land registry office. Typically used by registry administrators to
   * monitor or manage their assigned notary officers.
   */
  NotariesByRegistry(request: QueryNotariesByRegistryRequest): Promise<QueryNotariesByRegistryResponse>;
}

export const QueryServiceName = "elandnode.notary.v1.Query";
export class QueryClientImpl implements Query {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || QueryServiceName;
    this.rpc = rpc;
    this.Params = this.Params.bind(this);
    this.NotaryByNIC = this.NotaryByNIC.bind(this);
    this.NotaryByLicense = this.NotaryByLicense.bind(this);
    this.NotariesByRegistry = this.NotariesByRegistry.bind(this);
  }
  Params(request: QueryParamsRequest): Promise<QueryParamsResponse> {
    const data = QueryParamsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "Params", data);
    return promise.then((data) => QueryParamsResponse.decode(new BinaryReader(data)));
  }

  NotaryByNIC(request: QueryNotaryByNICRequest): Promise<QueryNotaryByNICResponse> {
    const data = QueryNotaryByNICRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "NotaryByNIC", data);
    return promise.then((data) => QueryNotaryByNICResponse.decode(new BinaryReader(data)));
  }

  NotaryByLicense(request: QueryNotaryByLicenseRequest): Promise<QueryNotaryByLicenseResponse> {
    const data = QueryNotaryByLicenseRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "NotaryByLicense", data);
    return promise.then((data) => QueryNotaryByLicenseResponse.decode(new BinaryReader(data)));
  }

  NotariesByRegistry(request: QueryNotariesByRegistryRequest): Promise<QueryNotariesByRegistryResponse> {
    const data = QueryNotariesByRegistryRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "NotariesByRegistry", data);
    return promise.then((data) => QueryNotariesByRegistryResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
