// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: elandnode/deed/v1/deed.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "elandnode.deed.v1";

export enum RequestType {
  REQUEST_TYPE_UNSPECIFIED = 0,
  REQUEST_TYPE_VIEW = 1,
  REQUEST_TYPE_DOWNLOAD = 2,
  UNRECOGNIZED = -1,
}

export function requestTypeFromJSON(object: any): RequestType {
  switch (object) {
    case 0:
    case "REQUEST_TYPE_UNSPECIFIED":
      return RequestType.REQUEST_TYPE_UNSPECIFIED;
    case 1:
    case "REQUEST_TYPE_VIEW":
      return RequestType.REQUEST_TYPE_VIEW;
    case 2:
    case "REQUEST_TYPE_DOWNLOAD":
      return RequestType.REQUEST_TYPE_DOWNLOAD;
    case -1:
    case "UNRECOGNIZED":
    default:
      return RequestType.UNRECOGNIZED;
  }
}

export function requestTypeToJSON(object: RequestType): string {
  switch (object) {
    case RequestType.REQUEST_TYPE_UNSPECIFIED:
      return "REQUEST_TYPE_UNSPECIFIED";
    case RequestType.REQUEST_TYPE_VIEW:
      return "REQUEST_TYPE_VIEW";
    case RequestType.REQUEST_TYPE_DOWNLOAD:
      return "REQUEST_TYPE_DOWNLOAD";
    case RequestType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Witness {
  name: string;
  nic: string;
  signatureHash: string;
}

export interface Deed {
  deedId: string;
  parcelId: string;
  folioId: string;
  deedNumber: string;
  sellerId: string;
  buyerId: string;
  notaryId: string;
  registryId: string;
  registeredDate: string;
  agreementCid: string;
  witnesses: Witness[];
  ownerCopyIssued: boolean;
  notaryCopyHeld: boolean;
  registryCopyFiled: boolean;
  notaryNic: string;
  /** notary_signature (base64) */
  notarySignature: string;
  /** signature_timestamp */
  signatureTimestamp: string;
}

export interface DeedRequest {
  requester: string;
  deedNumber: string;
  status: boolean;
  requestType: RequestType;
  createdAt: string;
  paid: boolean;
  remarks: string;
}

function createBaseWitness(): Witness {
  return { name: "", nic: "", signatureHash: "" };
}

export const Witness: MessageFns<Witness> = {
  encode(message: Witness, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.nic !== "") {
      writer.uint32(18).string(message.nic);
    }
    if (message.signatureHash !== "") {
      writer.uint32(26).string(message.signatureHash);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Witness {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWitness();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.nic = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.signatureHash = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Witness {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      nic: isSet(object.nic) ? globalThis.String(object.nic) : "",
      signatureHash: isSet(object.signatureHash) ? globalThis.String(object.signatureHash) : "",
    };
  },

  toJSON(message: Witness): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.nic !== "") {
      obj.nic = message.nic;
    }
    if (message.signatureHash !== "") {
      obj.signatureHash = message.signatureHash;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Witness>, I>>(base?: I): Witness {
    return Witness.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Witness>, I>>(object: I): Witness {
    const message = createBaseWitness();
    message.name = object.name ?? "";
    message.nic = object.nic ?? "";
    message.signatureHash = object.signatureHash ?? "";
    return message;
  },
};

function createBaseDeed(): Deed {
  return {
    deedId: "",
    parcelId: "",
    folioId: "",
    deedNumber: "",
    sellerId: "",
    buyerId: "",
    notaryId: "",
    registryId: "",
    registeredDate: "",
    agreementCid: "",
    witnesses: [],
    ownerCopyIssued: false,
    notaryCopyHeld: false,
    registryCopyFiled: false,
    notaryNic: "",
    notarySignature: "",
    signatureTimestamp: "",
  };
}

export const Deed: MessageFns<Deed> = {
  encode(message: Deed, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.deedId !== "") {
      writer.uint32(10).string(message.deedId);
    }
    if (message.parcelId !== "") {
      writer.uint32(18).string(message.parcelId);
    }
    if (message.folioId !== "") {
      writer.uint32(26).string(message.folioId);
    }
    if (message.deedNumber !== "") {
      writer.uint32(34).string(message.deedNumber);
    }
    if (message.sellerId !== "") {
      writer.uint32(42).string(message.sellerId);
    }
    if (message.buyerId !== "") {
      writer.uint32(50).string(message.buyerId);
    }
    if (message.notaryId !== "") {
      writer.uint32(58).string(message.notaryId);
    }
    if (message.registryId !== "") {
      writer.uint32(66).string(message.registryId);
    }
    if (message.registeredDate !== "") {
      writer.uint32(74).string(message.registeredDate);
    }
    if (message.agreementCid !== "") {
      writer.uint32(82).string(message.agreementCid);
    }
    for (const v of message.witnesses) {
      Witness.encode(v!, writer.uint32(90).fork()).join();
    }
    if (message.ownerCopyIssued !== false) {
      writer.uint32(96).bool(message.ownerCopyIssued);
    }
    if (message.notaryCopyHeld !== false) {
      writer.uint32(104).bool(message.notaryCopyHeld);
    }
    if (message.registryCopyFiled !== false) {
      writer.uint32(112).bool(message.registryCopyFiled);
    }
    if (message.notaryNic !== "") {
      writer.uint32(122).string(message.notaryNic);
    }
    if (message.notarySignature !== "") {
      writer.uint32(130).string(message.notarySignature);
    }
    if (message.signatureTimestamp !== "") {
      writer.uint32(138).string(message.signatureTimestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Deed {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeed();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.deedId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.parcelId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.folioId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.deedNumber = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.sellerId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.buyerId = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.notaryId = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.registryId = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.registeredDate = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.agreementCid = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.witnesses.push(Witness.decode(reader, reader.uint32()));
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.ownerCopyIssued = reader.bool();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.notaryCopyHeld = reader.bool();
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.registryCopyFiled = reader.bool();
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.notaryNic = reader.string();
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.notarySignature = reader.string();
          continue;
        }
        case 17: {
          if (tag !== 138) {
            break;
          }

          message.signatureTimestamp = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Deed {
    return {
      deedId: isSet(object.deedId) ? globalThis.String(object.deedId) : "",
      parcelId: isSet(object.parcelId) ? globalThis.String(object.parcelId) : "",
      folioId: isSet(object.folioId) ? globalThis.String(object.folioId) : "",
      deedNumber: isSet(object.deedNumber) ? globalThis.String(object.deedNumber) : "",
      sellerId: isSet(object.sellerId) ? globalThis.String(object.sellerId) : "",
      buyerId: isSet(object.buyerId) ? globalThis.String(object.buyerId) : "",
      notaryId: isSet(object.notaryId) ? globalThis.String(object.notaryId) : "",
      registryId: isSet(object.registryId) ? globalThis.String(object.registryId) : "",
      registeredDate: isSet(object.registeredDate) ? globalThis.String(object.registeredDate) : "",
      agreementCid: isSet(object.agreementCid) ? globalThis.String(object.agreementCid) : "",
      witnesses: globalThis.Array.isArray(object?.witnesses)
        ? object.witnesses.map((e: any) => Witness.fromJSON(e))
        : [],
      ownerCopyIssued: isSet(object.ownerCopyIssued) ? globalThis.Boolean(object.ownerCopyIssued) : false,
      notaryCopyHeld: isSet(object.notaryCopyHeld) ? globalThis.Boolean(object.notaryCopyHeld) : false,
      registryCopyFiled: isSet(object.registryCopyFiled) ? globalThis.Boolean(object.registryCopyFiled) : false,
      notaryNic: isSet(object.notaryNic) ? globalThis.String(object.notaryNic) : "",
      notarySignature: isSet(object.notarySignature) ? globalThis.String(object.notarySignature) : "",
      signatureTimestamp: isSet(object.signatureTimestamp) ? globalThis.String(object.signatureTimestamp) : "",
    };
  },

  toJSON(message: Deed): unknown {
    const obj: any = {};
    if (message.deedId !== "") {
      obj.deedId = message.deedId;
    }
    if (message.parcelId !== "") {
      obj.parcelId = message.parcelId;
    }
    if (message.folioId !== "") {
      obj.folioId = message.folioId;
    }
    if (message.deedNumber !== "") {
      obj.deedNumber = message.deedNumber;
    }
    if (message.sellerId !== "") {
      obj.sellerId = message.sellerId;
    }
    if (message.buyerId !== "") {
      obj.buyerId = message.buyerId;
    }
    if (message.notaryId !== "") {
      obj.notaryId = message.notaryId;
    }
    if (message.registryId !== "") {
      obj.registryId = message.registryId;
    }
    if (message.registeredDate !== "") {
      obj.registeredDate = message.registeredDate;
    }
    if (message.agreementCid !== "") {
      obj.agreementCid = message.agreementCid;
    }
    if (message.witnesses?.length) {
      obj.witnesses = message.witnesses.map((e) => Witness.toJSON(e));
    }
    if (message.ownerCopyIssued !== false) {
      obj.ownerCopyIssued = message.ownerCopyIssued;
    }
    if (message.notaryCopyHeld !== false) {
      obj.notaryCopyHeld = message.notaryCopyHeld;
    }
    if (message.registryCopyFiled !== false) {
      obj.registryCopyFiled = message.registryCopyFiled;
    }
    if (message.notaryNic !== "") {
      obj.notaryNic = message.notaryNic;
    }
    if (message.notarySignature !== "") {
      obj.notarySignature = message.notarySignature;
    }
    if (message.signatureTimestamp !== "") {
      obj.signatureTimestamp = message.signatureTimestamp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Deed>, I>>(base?: I): Deed {
    return Deed.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Deed>, I>>(object: I): Deed {
    const message = createBaseDeed();
    message.deedId = object.deedId ?? "";
    message.parcelId = object.parcelId ?? "";
    message.folioId = object.folioId ?? "";
    message.deedNumber = object.deedNumber ?? "";
    message.sellerId = object.sellerId ?? "";
    message.buyerId = object.buyerId ?? "";
    message.notaryId = object.notaryId ?? "";
    message.registryId = object.registryId ?? "";
    message.registeredDate = object.registeredDate ?? "";
    message.agreementCid = object.agreementCid ?? "";
    message.witnesses = object.witnesses?.map((e) => Witness.fromPartial(e)) || [];
    message.ownerCopyIssued = object.ownerCopyIssued ?? false;
    message.notaryCopyHeld = object.notaryCopyHeld ?? false;
    message.registryCopyFiled = object.registryCopyFiled ?? false;
    message.notaryNic = object.notaryNic ?? "";
    message.notarySignature = object.notarySignature ?? "";
    message.signatureTimestamp = object.signatureTimestamp ?? "";
    return message;
  },
};

function createBaseDeedRequest(): DeedRequest {
  return { requester: "", deedNumber: "", status: false, requestType: 0, createdAt: "", paid: false, remarks: "" };
}

export const DeedRequest: MessageFns<DeedRequest> = {
  encode(message: DeedRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requester !== "") {
      writer.uint32(10).string(message.requester);
    }
    if (message.deedNumber !== "") {
      writer.uint32(18).string(message.deedNumber);
    }
    if (message.status !== false) {
      writer.uint32(24).bool(message.status);
    }
    if (message.requestType !== 0) {
      writer.uint32(32).int32(message.requestType);
    }
    if (message.createdAt !== "") {
      writer.uint32(42).string(message.createdAt);
    }
    if (message.paid !== false) {
      writer.uint32(48).bool(message.paid);
    }
    if (message.remarks !== "") {
      writer.uint32(58).string(message.remarks);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeedRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeedRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.requester = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.deedNumber = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.status = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.requestType = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.paid = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.remarks = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeedRequest {
    return {
      requester: isSet(object.requester) ? globalThis.String(object.requester) : "",
      deedNumber: isSet(object.deedNumber) ? globalThis.String(object.deedNumber) : "",
      status: isSet(object.status) ? globalThis.Boolean(object.status) : false,
      requestType: isSet(object.requestType) ? requestTypeFromJSON(object.requestType) : 0,
      createdAt: isSet(object.createdAt) ? globalThis.String(object.createdAt) : "",
      paid: isSet(object.paid) ? globalThis.Boolean(object.paid) : false,
      remarks: isSet(object.remarks) ? globalThis.String(object.remarks) : "",
    };
  },

  toJSON(message: DeedRequest): unknown {
    const obj: any = {};
    if (message.requester !== "") {
      obj.requester = message.requester;
    }
    if (message.deedNumber !== "") {
      obj.deedNumber = message.deedNumber;
    }
    if (message.status !== false) {
      obj.status = message.status;
    }
    if (message.requestType !== 0) {
      obj.requestType = requestTypeToJSON(message.requestType);
    }
    if (message.createdAt !== "") {
      obj.createdAt = message.createdAt;
    }
    if (message.paid !== false) {
      obj.paid = message.paid;
    }
    if (message.remarks !== "") {
      obj.remarks = message.remarks;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeedRequest>, I>>(base?: I): DeedRequest {
    return DeedRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeedRequest>, I>>(object: I): DeedRequest {
    const message = createBaseDeedRequest();
    message.requester = object.requester ?? "";
    message.deedNumber = object.deedNumber ?? "";
    message.status = object.status ?? false;
    message.requestType = object.requestType ?? 0;
    message.createdAt = object.createdAt ?? "";
    message.paid = object.paid ?? false;
    message.remarks = object.remarks ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
