// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: elandnode/deed/v1/query.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { PageRequest, PageResponse } from "../../../cosmos/base/query/v1beta1/pagination";
import { Deed, DeedRequest } from "./deed";
import { Params } from "./params";

export const protobufPackage = "elandnode.deed.v1";

export interface QueryDeedByIdOwnerOrNotaryRequest {
  deedNumber: string;
  creator: string;
}

/** Response message for getting folio by ID */
export interface QueryDeedByIdOwnerOrNotaryResponse {
  status: string;
  code: number;
  message: string;
  deed: Deed | undefined;
  requestId: string;
  timestamp: string;
}

export interface QueryPendingDeedRequestsRequest {
  requester: string;
  pagination: PageRequest | undefined;
}

export interface QueryPendingDeedRequestsResponse {
  status: string;
  code: number;
  message: string;
  deedRequests: DeedRequest[];
  requestId: string;
  timestamp: string;
  pagination: PageResponse | undefined;
}

export interface QueryPendingDeedsRequest {
  requester: string;
  pagination: PageRequest | undefined;
}

export interface QueryPendingDeedsResponse {
  status: string;
  code: number;
  message: string;
  deeds: Deed[];
  requestId: string;
  timestamp: string;
  pagination: PageResponse | undefined;
}

export interface QueryDeedByNumberRequest {
  deedNumber: string;
}

export interface QueryDeedByNumberResponse {
  status: string;
  code: number;
  message: string;
  deed: Deed | undefined;
  requestId: string;
  timestamp: string;
}

/** QueryParamsRequest is request type for the Query/Params RPC method. */
export interface QueryParamsRequest {
}

/** QueryParamsResponse is response type for the Query/Params RPC method. */
export interface QueryParamsResponse {
  /** params holds all the parameters of this module. */
  params: Params | undefined;
}

function createBaseQueryDeedByIdOwnerOrNotaryRequest(): QueryDeedByIdOwnerOrNotaryRequest {
  return { deedNumber: "", creator: "" };
}

export const QueryDeedByIdOwnerOrNotaryRequest: MessageFns<QueryDeedByIdOwnerOrNotaryRequest> = {
  encode(message: QueryDeedByIdOwnerOrNotaryRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.deedNumber !== "") {
      writer.uint32(10).string(message.deedNumber);
    }
    if (message.creator !== "") {
      writer.uint32(18).string(message.creator);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryDeedByIdOwnerOrNotaryRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryDeedByIdOwnerOrNotaryRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.deedNumber = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryDeedByIdOwnerOrNotaryRequest {
    return {
      deedNumber: isSet(object.deedNumber) ? globalThis.String(object.deedNumber) : "",
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
    };
  },

  toJSON(message: QueryDeedByIdOwnerOrNotaryRequest): unknown {
    const obj: any = {};
    if (message.deedNumber !== "") {
      obj.deedNumber = message.deedNumber;
    }
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryDeedByIdOwnerOrNotaryRequest>, I>>(
    base?: I,
  ): QueryDeedByIdOwnerOrNotaryRequest {
    return QueryDeedByIdOwnerOrNotaryRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryDeedByIdOwnerOrNotaryRequest>, I>>(
    object: I,
  ): QueryDeedByIdOwnerOrNotaryRequest {
    const message = createBaseQueryDeedByIdOwnerOrNotaryRequest();
    message.deedNumber = object.deedNumber ?? "";
    message.creator = object.creator ?? "";
    return message;
  },
};

function createBaseQueryDeedByIdOwnerOrNotaryResponse(): QueryDeedByIdOwnerOrNotaryResponse {
  return { status: "", code: 0, message: "", deed: undefined, requestId: "", timestamp: "" };
}

export const QueryDeedByIdOwnerOrNotaryResponse: MessageFns<QueryDeedByIdOwnerOrNotaryResponse> = {
  encode(message: QueryDeedByIdOwnerOrNotaryResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.code !== 0) {
      writer.uint32(16).int32(message.code);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    if (message.deed !== undefined) {
      Deed.encode(message.deed, writer.uint32(34).fork()).join();
    }
    if (message.requestId !== "") {
      writer.uint32(42).string(message.requestId);
    }
    if (message.timestamp !== "") {
      writer.uint32(50).string(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryDeedByIdOwnerOrNotaryResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryDeedByIdOwnerOrNotaryResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.code = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.deed = Deed.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryDeedByIdOwnerOrNotaryResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      deed: isSet(object.deed) ? Deed.fromJSON(object.deed) : undefined,
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
    };
  },

  toJSON(message: QueryDeedByIdOwnerOrNotaryResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.deed !== undefined) {
      obj.deed = Deed.toJSON(message.deed);
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.timestamp !== "") {
      obj.timestamp = message.timestamp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryDeedByIdOwnerOrNotaryResponse>, I>>(
    base?: I,
  ): QueryDeedByIdOwnerOrNotaryResponse {
    return QueryDeedByIdOwnerOrNotaryResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryDeedByIdOwnerOrNotaryResponse>, I>>(
    object: I,
  ): QueryDeedByIdOwnerOrNotaryResponse {
    const message = createBaseQueryDeedByIdOwnerOrNotaryResponse();
    message.status = object.status ?? "";
    message.code = object.code ?? 0;
    message.message = object.message ?? "";
    message.deed = (object.deed !== undefined && object.deed !== null) ? Deed.fromPartial(object.deed) : undefined;
    message.requestId = object.requestId ?? "";
    message.timestamp = object.timestamp ?? "";
    return message;
  },
};

function createBaseQueryPendingDeedRequestsRequest(): QueryPendingDeedRequestsRequest {
  return { requester: "", pagination: undefined };
}

export const QueryPendingDeedRequestsRequest: MessageFns<QueryPendingDeedRequestsRequest> = {
  encode(message: QueryPendingDeedRequestsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requester !== "") {
      writer.uint32(10).string(message.requester);
    }
    if (message.pagination !== undefined) {
      PageRequest.encode(message.pagination, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryPendingDeedRequestsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryPendingDeedRequestsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.requester = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pagination = PageRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryPendingDeedRequestsRequest {
    return {
      requester: isSet(object.requester) ? globalThis.String(object.requester) : "",
      pagination: isSet(object.pagination) ? PageRequest.fromJSON(object.pagination) : undefined,
    };
  },

  toJSON(message: QueryPendingDeedRequestsRequest): unknown {
    const obj: any = {};
    if (message.requester !== "") {
      obj.requester = message.requester;
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageRequest.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryPendingDeedRequestsRequest>, I>>(base?: I): QueryPendingDeedRequestsRequest {
    return QueryPendingDeedRequestsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryPendingDeedRequestsRequest>, I>>(
    object: I,
  ): QueryPendingDeedRequestsRequest {
    const message = createBaseQueryPendingDeedRequestsRequest();
    message.requester = object.requester ?? "";
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageRequest.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseQueryPendingDeedRequestsResponse(): QueryPendingDeedRequestsResponse {
  return { status: "", code: 0, message: "", deedRequests: [], requestId: "", timestamp: "", pagination: undefined };
}

export const QueryPendingDeedRequestsResponse: MessageFns<QueryPendingDeedRequestsResponse> = {
  encode(message: QueryPendingDeedRequestsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.code !== 0) {
      writer.uint32(16).int32(message.code);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    for (const v of message.deedRequests) {
      DeedRequest.encode(v!, writer.uint32(34).fork()).join();
    }
    if (message.requestId !== "") {
      writer.uint32(42).string(message.requestId);
    }
    if (message.timestamp !== "") {
      writer.uint32(50).string(message.timestamp);
    }
    if (message.pagination !== undefined) {
      PageResponse.encode(message.pagination, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryPendingDeedRequestsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryPendingDeedRequestsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.code = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.deedRequests.push(DeedRequest.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.pagination = PageResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryPendingDeedRequestsResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      deedRequests: globalThis.Array.isArray(object?.deedRequests)
        ? object.deedRequests.map((e: any) => DeedRequest.fromJSON(e))
        : [],
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
      pagination: isSet(object.pagination) ? PageResponse.fromJSON(object.pagination) : undefined,
    };
  },

  toJSON(message: QueryPendingDeedRequestsResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.deedRequests?.length) {
      obj.deedRequests = message.deedRequests.map((e) => DeedRequest.toJSON(e));
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.timestamp !== "") {
      obj.timestamp = message.timestamp;
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageResponse.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryPendingDeedRequestsResponse>, I>>(
    base?: I,
  ): QueryPendingDeedRequestsResponse {
    return QueryPendingDeedRequestsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryPendingDeedRequestsResponse>, I>>(
    object: I,
  ): QueryPendingDeedRequestsResponse {
    const message = createBaseQueryPendingDeedRequestsResponse();
    message.status = object.status ?? "";
    message.code = object.code ?? 0;
    message.message = object.message ?? "";
    message.deedRequests = object.deedRequests?.map((e) => DeedRequest.fromPartial(e)) || [];
    message.requestId = object.requestId ?? "";
    message.timestamp = object.timestamp ?? "";
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageResponse.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseQueryPendingDeedsRequest(): QueryPendingDeedsRequest {
  return { requester: "", pagination: undefined };
}

export const QueryPendingDeedsRequest: MessageFns<QueryPendingDeedsRequest> = {
  encode(message: QueryPendingDeedsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requester !== "") {
      writer.uint32(10).string(message.requester);
    }
    if (message.pagination !== undefined) {
      PageRequest.encode(message.pagination, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryPendingDeedsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryPendingDeedsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.requester = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pagination = PageRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryPendingDeedsRequest {
    return {
      requester: isSet(object.requester) ? globalThis.String(object.requester) : "",
      pagination: isSet(object.pagination) ? PageRequest.fromJSON(object.pagination) : undefined,
    };
  },

  toJSON(message: QueryPendingDeedsRequest): unknown {
    const obj: any = {};
    if (message.requester !== "") {
      obj.requester = message.requester;
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageRequest.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryPendingDeedsRequest>, I>>(base?: I): QueryPendingDeedsRequest {
    return QueryPendingDeedsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryPendingDeedsRequest>, I>>(object: I): QueryPendingDeedsRequest {
    const message = createBaseQueryPendingDeedsRequest();
    message.requester = object.requester ?? "";
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageRequest.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseQueryPendingDeedsResponse(): QueryPendingDeedsResponse {
  return { status: "", code: 0, message: "", deeds: [], requestId: "", timestamp: "", pagination: undefined };
}

export const QueryPendingDeedsResponse: MessageFns<QueryPendingDeedsResponse> = {
  encode(message: QueryPendingDeedsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.code !== 0) {
      writer.uint32(16).int32(message.code);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    for (const v of message.deeds) {
      Deed.encode(v!, writer.uint32(34).fork()).join();
    }
    if (message.requestId !== "") {
      writer.uint32(42).string(message.requestId);
    }
    if (message.timestamp !== "") {
      writer.uint32(50).string(message.timestamp);
    }
    if (message.pagination !== undefined) {
      PageResponse.encode(message.pagination, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryPendingDeedsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryPendingDeedsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.code = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.deeds.push(Deed.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.pagination = PageResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryPendingDeedsResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      deeds: globalThis.Array.isArray(object?.deeds) ? object.deeds.map((e: any) => Deed.fromJSON(e)) : [],
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
      pagination: isSet(object.pagination) ? PageResponse.fromJSON(object.pagination) : undefined,
    };
  },

  toJSON(message: QueryPendingDeedsResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.deeds?.length) {
      obj.deeds = message.deeds.map((e) => Deed.toJSON(e));
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.timestamp !== "") {
      obj.timestamp = message.timestamp;
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageResponse.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryPendingDeedsResponse>, I>>(base?: I): QueryPendingDeedsResponse {
    return QueryPendingDeedsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryPendingDeedsResponse>, I>>(object: I): QueryPendingDeedsResponse {
    const message = createBaseQueryPendingDeedsResponse();
    message.status = object.status ?? "";
    message.code = object.code ?? 0;
    message.message = object.message ?? "";
    message.deeds = object.deeds?.map((e) => Deed.fromPartial(e)) || [];
    message.requestId = object.requestId ?? "";
    message.timestamp = object.timestamp ?? "";
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageResponse.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseQueryDeedByNumberRequest(): QueryDeedByNumberRequest {
  return { deedNumber: "" };
}

export const QueryDeedByNumberRequest: MessageFns<QueryDeedByNumberRequest> = {
  encode(message: QueryDeedByNumberRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.deedNumber !== "") {
      writer.uint32(10).string(message.deedNumber);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryDeedByNumberRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryDeedByNumberRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.deedNumber = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryDeedByNumberRequest {
    return { deedNumber: isSet(object.deedNumber) ? globalThis.String(object.deedNumber) : "" };
  },

  toJSON(message: QueryDeedByNumberRequest): unknown {
    const obj: any = {};
    if (message.deedNumber !== "") {
      obj.deedNumber = message.deedNumber;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryDeedByNumberRequest>, I>>(base?: I): QueryDeedByNumberRequest {
    return QueryDeedByNumberRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryDeedByNumberRequest>, I>>(object: I): QueryDeedByNumberRequest {
    const message = createBaseQueryDeedByNumberRequest();
    message.deedNumber = object.deedNumber ?? "";
    return message;
  },
};

function createBaseQueryDeedByNumberResponse(): QueryDeedByNumberResponse {
  return { status: "", code: 0, message: "", deed: undefined, requestId: "", timestamp: "" };
}

export const QueryDeedByNumberResponse: MessageFns<QueryDeedByNumberResponse> = {
  encode(message: QueryDeedByNumberResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.code !== 0) {
      writer.uint32(16).int32(message.code);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    if (message.deed !== undefined) {
      Deed.encode(message.deed, writer.uint32(34).fork()).join();
    }
    if (message.requestId !== "") {
      writer.uint32(42).string(message.requestId);
    }
    if (message.timestamp !== "") {
      writer.uint32(50).string(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryDeedByNumberResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryDeedByNumberResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.code = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.deed = Deed.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryDeedByNumberResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      deed: isSet(object.deed) ? Deed.fromJSON(object.deed) : undefined,
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
    };
  },

  toJSON(message: QueryDeedByNumberResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.deed !== undefined) {
      obj.deed = Deed.toJSON(message.deed);
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.timestamp !== "") {
      obj.timestamp = message.timestamp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryDeedByNumberResponse>, I>>(base?: I): QueryDeedByNumberResponse {
    return QueryDeedByNumberResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryDeedByNumberResponse>, I>>(object: I): QueryDeedByNumberResponse {
    const message = createBaseQueryDeedByNumberResponse();
    message.status = object.status ?? "";
    message.code = object.code ?? 0;
    message.message = object.message ?? "";
    message.deed = (object.deed !== undefined && object.deed !== null) ? Deed.fromPartial(object.deed) : undefined;
    message.requestId = object.requestId ?? "";
    message.timestamp = object.timestamp ?? "";
    return message;
  },
};

function createBaseQueryParamsRequest(): QueryParamsRequest {
  return {};
}

export const QueryParamsRequest: MessageFns<QueryParamsRequest> = {
  encode(_: QueryParamsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryParamsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): QueryParamsRequest {
    return {};
  },

  toJSON(_: QueryParamsRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(base?: I): QueryParamsRequest {
    return QueryParamsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(_: I): QueryParamsRequest {
    const message = createBaseQueryParamsRequest();
    return message;
  },
};

function createBaseQueryParamsResponse(): QueryParamsResponse {
  return { params: undefined };
}

export const QueryParamsResponse: MessageFns<QueryParamsResponse> = {
  encode(message: QueryParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryParamsResponse {
    return { params: isSet(object.params) ? Params.fromJSON(object.params) : undefined };
  },

  toJSON(message: QueryParamsResponse): unknown {
    const obj: any = {};
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(base?: I): QueryParamsResponse {
    return QueryParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(object: I): QueryParamsResponse {
    const message = createBaseQueryParamsResponse();
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

/** Query defines the gRPC querier service. */
export interface Query {
  /**
   * DeedByNumber retrieves detailed information about a specific deed
   * using its unique deed number. This query helps trace a property's
   * registration history and ownership chain.
   */
  DeedByNumber(request: QueryDeedByNumberRequest): Promise<QueryDeedByNumberResponse>;
  /**
   * PendingDeeds returns a list of all deeds that have been prepared
   * but not yet officially issued by the registry. Typically used by
   * registry officers to review and approve pending deed records.
   */
  PendingDeeds(request: QueryPendingDeedsRequest): Promise<QueryPendingDeedsResponse>;
  /**
   * PendingDeedRequests returns all deed requests that are awaiting
   * registry approval. This is part of the deed request and approval
   * workflow managed by registry offices.
   */
  PendingDeedRequests(request: QueryPendingDeedRequestsRequest): Promise<QueryPendingDeedRequestsResponse>;
  /**
   * DeedByIdOwnerOrNotary retrieves a deed by its number, but only if
   * the requesting address belongs to the registered owner or an authorized
   * notary. This enforces restricted access to sensitive deed data.
   */
  DeedByIdOwnerOrNotary(request: QueryDeedByIdOwnerOrNotaryRequest): Promise<QueryDeedByIdOwnerOrNotaryResponse>;
}

export const QueryServiceName = "elandnode.deed.v1.Query";
export class QueryClientImpl implements Query {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || QueryServiceName;
    this.rpc = rpc;
    this.DeedByNumber = this.DeedByNumber.bind(this);
    this.PendingDeeds = this.PendingDeeds.bind(this);
    this.PendingDeedRequests = this.PendingDeedRequests.bind(this);
    this.DeedByIdOwnerOrNotary = this.DeedByIdOwnerOrNotary.bind(this);
  }
  DeedByNumber(request: QueryDeedByNumberRequest): Promise<QueryDeedByNumberResponse> {
    const data = QueryDeedByNumberRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "DeedByNumber", data);
    return promise.then((data) => QueryDeedByNumberResponse.decode(new BinaryReader(data)));
  }

  PendingDeeds(request: QueryPendingDeedsRequest): Promise<QueryPendingDeedsResponse> {
    const data = QueryPendingDeedsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "PendingDeeds", data);
    return promise.then((data) => QueryPendingDeedsResponse.decode(new BinaryReader(data)));
  }

  PendingDeedRequests(request: QueryPendingDeedRequestsRequest): Promise<QueryPendingDeedRequestsResponse> {
    const data = QueryPendingDeedRequestsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "PendingDeedRequests", data);
    return promise.then((data) => QueryPendingDeedRequestsResponse.decode(new BinaryReader(data)));
  }

  DeedByIdOwnerOrNotary(request: QueryDeedByIdOwnerOrNotaryRequest): Promise<QueryDeedByIdOwnerOrNotaryResponse> {
    const data = QueryDeedByIdOwnerOrNotaryRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "DeedByIdOwnerOrNotary", data);
    return promise.then((data) => QueryDeedByIdOwnerOrNotaryResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
