// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: elandnode/survey/v1/survey.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "elandnode.survey.v1";

export interface SurveyPlan {
  planId: string;
  parcelId: string;
  surveyorId: string;
  surveyDate: string;
  planCid: string;
  verified: boolean;
}

export interface SurveyOffice {
  surveyorId: string;
  district: string;
  location: string;
  contact: string;
  active: boolean;
}

function createBaseSurveyPlan(): SurveyPlan {
  return { planId: "", parcelId: "", surveyorId: "", surveyDate: "", planCid: "", verified: false };
}

export const SurveyPlan: MessageFns<SurveyPlan> = {
  encode(message: SurveyPlan, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.planId !== "") {
      writer.uint32(10).string(message.planId);
    }
    if (message.parcelId !== "") {
      writer.uint32(18).string(message.parcelId);
    }
    if (message.surveyorId !== "") {
      writer.uint32(26).string(message.surveyorId);
    }
    if (message.surveyDate !== "") {
      writer.uint32(34).string(message.surveyDate);
    }
    if (message.planCid !== "") {
      writer.uint32(42).string(message.planCid);
    }
    if (message.verified !== false) {
      writer.uint32(48).bool(message.verified);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SurveyPlan {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSurveyPlan();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.planId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.parcelId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.surveyorId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.surveyDate = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.planCid = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.verified = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SurveyPlan {
    return {
      planId: isSet(object.planId) ? globalThis.String(object.planId) : "",
      parcelId: isSet(object.parcelId) ? globalThis.String(object.parcelId) : "",
      surveyorId: isSet(object.surveyorId) ? globalThis.String(object.surveyorId) : "",
      surveyDate: isSet(object.surveyDate) ? globalThis.String(object.surveyDate) : "",
      planCid: isSet(object.planCid) ? globalThis.String(object.planCid) : "",
      verified: isSet(object.verified) ? globalThis.Boolean(object.verified) : false,
    };
  },

  toJSON(message: SurveyPlan): unknown {
    const obj: any = {};
    if (message.planId !== "") {
      obj.planId = message.planId;
    }
    if (message.parcelId !== "") {
      obj.parcelId = message.parcelId;
    }
    if (message.surveyorId !== "") {
      obj.surveyorId = message.surveyorId;
    }
    if (message.surveyDate !== "") {
      obj.surveyDate = message.surveyDate;
    }
    if (message.planCid !== "") {
      obj.planCid = message.planCid;
    }
    if (message.verified !== false) {
      obj.verified = message.verified;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SurveyPlan>, I>>(base?: I): SurveyPlan {
    return SurveyPlan.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SurveyPlan>, I>>(object: I): SurveyPlan {
    const message = createBaseSurveyPlan();
    message.planId = object.planId ?? "";
    message.parcelId = object.parcelId ?? "";
    message.surveyorId = object.surveyorId ?? "";
    message.surveyDate = object.surveyDate ?? "";
    message.planCid = object.planCid ?? "";
    message.verified = object.verified ?? false;
    return message;
  },
};

function createBaseSurveyOffice(): SurveyOffice {
  return { surveyorId: "", district: "", location: "", contact: "", active: false };
}

export const SurveyOffice: MessageFns<SurveyOffice> = {
  encode(message: SurveyOffice, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.surveyorId !== "") {
      writer.uint32(10).string(message.surveyorId);
    }
    if (message.district !== "") {
      writer.uint32(18).string(message.district);
    }
    if (message.location !== "") {
      writer.uint32(26).string(message.location);
    }
    if (message.contact !== "") {
      writer.uint32(34).string(message.contact);
    }
    if (message.active !== false) {
      writer.uint32(40).bool(message.active);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SurveyOffice {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSurveyOffice();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.surveyorId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.district = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.location = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.contact = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.active = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SurveyOffice {
    return {
      surveyorId: isSet(object.surveyorId) ? globalThis.String(object.surveyorId) : "",
      district: isSet(object.district) ? globalThis.String(object.district) : "",
      location: isSet(object.location) ? globalThis.String(object.location) : "",
      contact: isSet(object.contact) ? globalThis.String(object.contact) : "",
      active: isSet(object.active) ? globalThis.Boolean(object.active) : false,
    };
  },

  toJSON(message: SurveyOffice): unknown {
    const obj: any = {};
    if (message.surveyorId !== "") {
      obj.surveyorId = message.surveyorId;
    }
    if (message.district !== "") {
      obj.district = message.district;
    }
    if (message.location !== "") {
      obj.location = message.location;
    }
    if (message.contact !== "") {
      obj.contact = message.contact;
    }
    if (message.active !== false) {
      obj.active = message.active;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SurveyOffice>, I>>(base?: I): SurveyOffice {
    return SurveyOffice.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SurveyOffice>, I>>(object: I): SurveyOffice {
    const message = createBaseSurveyOffice();
    message.surveyorId = object.surveyorId ?? "";
    message.district = object.district ?? "";
    message.location = object.location ?? "";
    message.contact = object.contact ?? "";
    message.active = object.active ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
