// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: elandnode/survey/v1/tx.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "elandnode.survey.v1";

export interface MsgVerifySurveyPlan {
  creator: string;
  planId: string;
  approved: boolean;
  remarks: string;
}

export interface MsgVerifySurveyPlanResponse {
  status: string;
  code: number;
  message: string;
  data: string;
  requestId: string;
  timestamp: string;
}

export interface MsgSubmitSurveyPlan {
  surveyor: string;
  planId: string;
  parcelId: string;
  surveyDate: string;
  planCid: string;
  creator: string;
}

export interface MsgSubmitSurveyPlanResponse {
  status: string;
  code: number;
  message: string;
  data: string;
  requestId: string;
  timestamp: string;
}

export interface MsgRegisterSurveyor {
  surveyorId: string;
  nic: string;
  name: string;
  contact: string;
  address: string;
  district: string;
  creator: string;
  location: string;
}

export interface MsgRegisterSurveyorResponse {
  status: string;
  code: number;
  message: string;
  data: string;
  requestId: string;
  timestamp: string;
}

function createBaseMsgVerifySurveyPlan(): MsgVerifySurveyPlan {
  return { creator: "", planId: "", approved: false, remarks: "" };
}

export const MsgVerifySurveyPlan: MessageFns<MsgVerifySurveyPlan> = {
  encode(message: MsgVerifySurveyPlan, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.planId !== "") {
      writer.uint32(18).string(message.planId);
    }
    if (message.approved !== false) {
      writer.uint32(24).bool(message.approved);
    }
    if (message.remarks !== "") {
      writer.uint32(34).string(message.remarks);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgVerifySurveyPlan {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgVerifySurveyPlan();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.planId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.approved = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.remarks = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgVerifySurveyPlan {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      planId: isSet(object.planId) ? globalThis.String(object.planId) : "",
      approved: isSet(object.approved) ? globalThis.Boolean(object.approved) : false,
      remarks: isSet(object.remarks) ? globalThis.String(object.remarks) : "",
    };
  },

  toJSON(message: MsgVerifySurveyPlan): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.planId !== "") {
      obj.planId = message.planId;
    }
    if (message.approved !== false) {
      obj.approved = message.approved;
    }
    if (message.remarks !== "") {
      obj.remarks = message.remarks;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgVerifySurveyPlan>, I>>(base?: I): MsgVerifySurveyPlan {
    return MsgVerifySurveyPlan.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgVerifySurveyPlan>, I>>(object: I): MsgVerifySurveyPlan {
    const message = createBaseMsgVerifySurveyPlan();
    message.creator = object.creator ?? "";
    message.planId = object.planId ?? "";
    message.approved = object.approved ?? false;
    message.remarks = object.remarks ?? "";
    return message;
  },
};

function createBaseMsgVerifySurveyPlanResponse(): MsgVerifySurveyPlanResponse {
  return { status: "", code: 0, message: "", data: "", requestId: "", timestamp: "" };
}

export const MsgVerifySurveyPlanResponse: MessageFns<MsgVerifySurveyPlanResponse> = {
  encode(message: MsgVerifySurveyPlanResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.code !== 0) {
      writer.uint32(16).int32(message.code);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    if (message.data !== "") {
      writer.uint32(34).string(message.data);
    }
    if (message.requestId !== "") {
      writer.uint32(42).string(message.requestId);
    }
    if (message.timestamp !== "") {
      writer.uint32(50).string(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgVerifySurveyPlanResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgVerifySurveyPlanResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.code = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.data = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgVerifySurveyPlanResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      data: isSet(object.data) ? globalThis.String(object.data) : "",
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
    };
  },

  toJSON(message: MsgVerifySurveyPlanResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.data !== "") {
      obj.data = message.data;
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.timestamp !== "") {
      obj.timestamp = message.timestamp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgVerifySurveyPlanResponse>, I>>(base?: I): MsgVerifySurveyPlanResponse {
    return MsgVerifySurveyPlanResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgVerifySurveyPlanResponse>, I>>(object: I): MsgVerifySurveyPlanResponse {
    const message = createBaseMsgVerifySurveyPlanResponse();
    message.status = object.status ?? "";
    message.code = object.code ?? 0;
    message.message = object.message ?? "";
    message.data = object.data ?? "";
    message.requestId = object.requestId ?? "";
    message.timestamp = object.timestamp ?? "";
    return message;
  },
};

function createBaseMsgSubmitSurveyPlan(): MsgSubmitSurveyPlan {
  return { surveyor: "", planId: "", parcelId: "", surveyDate: "", planCid: "", creator: "" };
}

export const MsgSubmitSurveyPlan: MessageFns<MsgSubmitSurveyPlan> = {
  encode(message: MsgSubmitSurveyPlan, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.surveyor !== "") {
      writer.uint32(10).string(message.surveyor);
    }
    if (message.planId !== "") {
      writer.uint32(18).string(message.planId);
    }
    if (message.parcelId !== "") {
      writer.uint32(26).string(message.parcelId);
    }
    if (message.surveyDate !== "") {
      writer.uint32(34).string(message.surveyDate);
    }
    if (message.planCid !== "") {
      writer.uint32(42).string(message.planCid);
    }
    if (message.creator !== "") {
      writer.uint32(50).string(message.creator);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSubmitSurveyPlan {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSubmitSurveyPlan();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.surveyor = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.planId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.parcelId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.surveyDate = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.planCid = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgSubmitSurveyPlan {
    return {
      surveyor: isSet(object.surveyor) ? globalThis.String(object.surveyor) : "",
      planId: isSet(object.planId) ? globalThis.String(object.planId) : "",
      parcelId: isSet(object.parcelId) ? globalThis.String(object.parcelId) : "",
      surveyDate: isSet(object.surveyDate) ? globalThis.String(object.surveyDate) : "",
      planCid: isSet(object.planCid) ? globalThis.String(object.planCid) : "",
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
    };
  },

  toJSON(message: MsgSubmitSurveyPlan): unknown {
    const obj: any = {};
    if (message.surveyor !== "") {
      obj.surveyor = message.surveyor;
    }
    if (message.planId !== "") {
      obj.planId = message.planId;
    }
    if (message.parcelId !== "") {
      obj.parcelId = message.parcelId;
    }
    if (message.surveyDate !== "") {
      obj.surveyDate = message.surveyDate;
    }
    if (message.planCid !== "") {
      obj.planCid = message.planCid;
    }
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSubmitSurveyPlan>, I>>(base?: I): MsgSubmitSurveyPlan {
    return MsgSubmitSurveyPlan.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSubmitSurveyPlan>, I>>(object: I): MsgSubmitSurveyPlan {
    const message = createBaseMsgSubmitSurveyPlan();
    message.surveyor = object.surveyor ?? "";
    message.planId = object.planId ?? "";
    message.parcelId = object.parcelId ?? "";
    message.surveyDate = object.surveyDate ?? "";
    message.planCid = object.planCid ?? "";
    message.creator = object.creator ?? "";
    return message;
  },
};

function createBaseMsgSubmitSurveyPlanResponse(): MsgSubmitSurveyPlanResponse {
  return { status: "", code: 0, message: "", data: "", requestId: "", timestamp: "" };
}

export const MsgSubmitSurveyPlanResponse: MessageFns<MsgSubmitSurveyPlanResponse> = {
  encode(message: MsgSubmitSurveyPlanResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.code !== 0) {
      writer.uint32(16).int32(message.code);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    if (message.data !== "") {
      writer.uint32(34).string(message.data);
    }
    if (message.requestId !== "") {
      writer.uint32(42).string(message.requestId);
    }
    if (message.timestamp !== "") {
      writer.uint32(50).string(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSubmitSurveyPlanResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSubmitSurveyPlanResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.code = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.data = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgSubmitSurveyPlanResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      data: isSet(object.data) ? globalThis.String(object.data) : "",
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
    };
  },

  toJSON(message: MsgSubmitSurveyPlanResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.data !== "") {
      obj.data = message.data;
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.timestamp !== "") {
      obj.timestamp = message.timestamp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSubmitSurveyPlanResponse>, I>>(base?: I): MsgSubmitSurveyPlanResponse {
    return MsgSubmitSurveyPlanResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSubmitSurveyPlanResponse>, I>>(object: I): MsgSubmitSurveyPlanResponse {
    const message = createBaseMsgSubmitSurveyPlanResponse();
    message.status = object.status ?? "";
    message.code = object.code ?? 0;
    message.message = object.message ?? "";
    message.data = object.data ?? "";
    message.requestId = object.requestId ?? "";
    message.timestamp = object.timestamp ?? "";
    return message;
  },
};

function createBaseMsgRegisterSurveyor(): MsgRegisterSurveyor {
  return { surveyorId: "", nic: "", name: "", contact: "", address: "", district: "", creator: "", location: "" };
}

export const MsgRegisterSurveyor: MessageFns<MsgRegisterSurveyor> = {
  encode(message: MsgRegisterSurveyor, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.surveyorId !== "") {
      writer.uint32(10).string(message.surveyorId);
    }
    if (message.nic !== "") {
      writer.uint32(18).string(message.nic);
    }
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    if (message.contact !== "") {
      writer.uint32(34).string(message.contact);
    }
    if (message.address !== "") {
      writer.uint32(42).string(message.address);
    }
    if (message.district !== "") {
      writer.uint32(50).string(message.district);
    }
    if (message.creator !== "") {
      writer.uint32(58).string(message.creator);
    }
    if (message.location !== "") {
      writer.uint32(66).string(message.location);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRegisterSurveyor {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgRegisterSurveyor();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.surveyorId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.nic = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.contact = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.address = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.district = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.location = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgRegisterSurveyor {
    return {
      surveyorId: isSet(object.surveyorId) ? globalThis.String(object.surveyorId) : "",
      nic: isSet(object.nic) ? globalThis.String(object.nic) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      contact: isSet(object.contact) ? globalThis.String(object.contact) : "",
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      district: isSet(object.district) ? globalThis.String(object.district) : "",
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      location: isSet(object.location) ? globalThis.String(object.location) : "",
    };
  },

  toJSON(message: MsgRegisterSurveyor): unknown {
    const obj: any = {};
    if (message.surveyorId !== "") {
      obj.surveyorId = message.surveyorId;
    }
    if (message.nic !== "") {
      obj.nic = message.nic;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.contact !== "") {
      obj.contact = message.contact;
    }
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (message.district !== "") {
      obj.district = message.district;
    }
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.location !== "") {
      obj.location = message.location;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRegisterSurveyor>, I>>(base?: I): MsgRegisterSurveyor {
    return MsgRegisterSurveyor.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRegisterSurveyor>, I>>(object: I): MsgRegisterSurveyor {
    const message = createBaseMsgRegisterSurveyor();
    message.surveyorId = object.surveyorId ?? "";
    message.nic = object.nic ?? "";
    message.name = object.name ?? "";
    message.contact = object.contact ?? "";
    message.address = object.address ?? "";
    message.district = object.district ?? "";
    message.creator = object.creator ?? "";
    message.location = object.location ?? "";
    return message;
  },
};

function createBaseMsgRegisterSurveyorResponse(): MsgRegisterSurveyorResponse {
  return { status: "", code: 0, message: "", data: "", requestId: "", timestamp: "" };
}

export const MsgRegisterSurveyorResponse: MessageFns<MsgRegisterSurveyorResponse> = {
  encode(message: MsgRegisterSurveyorResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.code !== 0) {
      writer.uint32(16).int32(message.code);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    if (message.data !== "") {
      writer.uint32(34).string(message.data);
    }
    if (message.requestId !== "") {
      writer.uint32(42).string(message.requestId);
    }
    if (message.timestamp !== "") {
      writer.uint32(50).string(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRegisterSurveyorResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgRegisterSurveyorResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.code = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.data = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgRegisterSurveyorResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      data: isSet(object.data) ? globalThis.String(object.data) : "",
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
    };
  },

  toJSON(message: MsgRegisterSurveyorResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.data !== "") {
      obj.data = message.data;
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.timestamp !== "") {
      obj.timestamp = message.timestamp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRegisterSurveyorResponse>, I>>(base?: I): MsgRegisterSurveyorResponse {
    return MsgRegisterSurveyorResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRegisterSurveyorResponse>, I>>(object: I): MsgRegisterSurveyorResponse {
    const message = createBaseMsgRegisterSurveyorResponse();
    message.status = object.status ?? "";
    message.code = object.code ?? 0;
    message.message = object.message ?? "";
    message.data = object.data ?? "";
    message.requestId = object.requestId ?? "";
    message.timestamp = object.timestamp ?? "";
    return message;
  },
};

/** Msg defines the Msg service. */
export interface Msg {
  /**
   * RegisterSurveyor allows a Land Registry or Survey Department administrator
   * to register a new surveyor on-chain. The surveyor’s identity, NIC/license,
   * district, and contact details are recorded and the account is marked active
   * for submitting and signing survey plans.
   */
  RegisterSurveyor(request: MsgRegisterSurveyor): Promise<MsgRegisterSurveyorResponse>;
  /**
   * SubmitSurveyPlan lets an authorized surveyor submit a survey plan for a parcel.
   * The plan metadata (plan_id, parcel_id, survey date, IPFS CID, etc.) is stored
   * in a pending (unverified) state and emits a `survey_plan_submitted` event.
   */
  SubmitSurveyPlan(request: MsgSubmitSurveyPlan): Promise<MsgSubmitSurveyPlanResponse>;
  /**
   * VerifySurveyPlan enables a Survey Department officer (or authorized registry officer)
   * to review and verify a previously submitted survey plan. Successful verification
   * marks the plan as approved, allowing the parcel to be registered or linked to a folio,
   * and emits a `survey_plan_verified` event.
   */
  VerifySurveyPlan(request: MsgVerifySurveyPlan): Promise<MsgVerifySurveyPlanResponse>;
}

export const MsgServiceName = "elandnode.survey.v1.Msg";
export class MsgClientImpl implements Msg {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || MsgServiceName;
    this.rpc = rpc;
    this.RegisterSurveyor = this.RegisterSurveyor.bind(this);
    this.SubmitSurveyPlan = this.SubmitSurveyPlan.bind(this);
    this.VerifySurveyPlan = this.VerifySurveyPlan.bind(this);
  }
  RegisterSurveyor(request: MsgRegisterSurveyor): Promise<MsgRegisterSurveyorResponse> {
    const data = MsgRegisterSurveyor.encode(request).finish();
    const promise = this.rpc.request(this.service, "RegisterSurveyor", data);
    return promise.then((data) => MsgRegisterSurveyorResponse.decode(new BinaryReader(data)));
  }

  SubmitSurveyPlan(request: MsgSubmitSurveyPlan): Promise<MsgSubmitSurveyPlanResponse> {
    const data = MsgSubmitSurveyPlan.encode(request).finish();
    const promise = this.rpc.request(this.service, "SubmitSurveyPlan", data);
    return promise.then((data) => MsgSubmitSurveyPlanResponse.decode(new BinaryReader(data)));
  }

  VerifySurveyPlan(request: MsgVerifySurveyPlan): Promise<MsgVerifySurveyPlanResponse> {
    const data = MsgVerifySurveyPlan.encode(request).finish();
    const promise = this.rpc.request(this.service, "VerifySurveyPlan", data);
    return promise.then((data) => MsgVerifySurveyPlanResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
