// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: elandnode/folio/v1/folio.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "elandnode.folio.v1";

export enum RequestType {
  REQUEST_TYPE_UNSPECIFIED = 0,
  REQUEST_TYPE_VIEW = 1,
  REQUEST_TYPE_DOWNLOAD = 2,
  UNRECOGNIZED = -1,
}

export function requestTypeFromJSON(object: any): RequestType {
  switch (object) {
    case 0:
    case "REQUEST_TYPE_UNSPECIFIED":
      return RequestType.REQUEST_TYPE_UNSPECIFIED;
    case 1:
    case "REQUEST_TYPE_VIEW":
      return RequestType.REQUEST_TYPE_VIEW;
    case 2:
    case "REQUEST_TYPE_DOWNLOAD":
      return RequestType.REQUEST_TYPE_DOWNLOAD;
    case -1:
    case "UNRECOGNIZED":
    default:
      return RequestType.UNRECOGNIZED;
  }
}

export function requestTypeToJSON(object: RequestType): string {
  switch (object) {
    case RequestType.REQUEST_TYPE_UNSPECIFIED:
      return "REQUEST_TYPE_UNSPECIFIED";
    case RequestType.REQUEST_TYPE_VIEW:
      return "REQUEST_TYPE_VIEW";
    case RequestType.REQUEST_TYPE_DOWNLOAD:
      return "REQUEST_TYPE_DOWNLOAD";
    case RequestType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Folio {
  folioId: string;
  parcelId: string;
  registryId: string;
  folioNumber: string;
  landDescription: string;
  extent: string;
  deedIds: string[];
  currentDeedId: string;
  createdAt: string;
  updatedAt: string;
}

export interface StringArray {
  values: string[];
}

export interface FolioRequest {
  requester: string;
  folioId: string;
  status: boolean;
  requestType: RequestType;
  createdAt: string;
  paid: boolean;
  remarks: string;
}

function createBaseFolio(): Folio {
  return {
    folioId: "",
    parcelId: "",
    registryId: "",
    folioNumber: "",
    landDescription: "",
    extent: "",
    deedIds: [],
    currentDeedId: "",
    createdAt: "",
    updatedAt: "",
  };
}

export const Folio: MessageFns<Folio> = {
  encode(message: Folio, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.folioId !== "") {
      writer.uint32(10).string(message.folioId);
    }
    if (message.parcelId !== "") {
      writer.uint32(18).string(message.parcelId);
    }
    if (message.registryId !== "") {
      writer.uint32(26).string(message.registryId);
    }
    if (message.folioNumber !== "") {
      writer.uint32(34).string(message.folioNumber);
    }
    if (message.landDescription !== "") {
      writer.uint32(42).string(message.landDescription);
    }
    if (message.extent !== "") {
      writer.uint32(50).string(message.extent);
    }
    for (const v of message.deedIds) {
      writer.uint32(58).string(v!);
    }
    if (message.currentDeedId !== "") {
      writer.uint32(66).string(message.currentDeedId);
    }
    if (message.createdAt !== "") {
      writer.uint32(74).string(message.createdAt);
    }
    if (message.updatedAt !== "") {
      writer.uint32(82).string(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Folio {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFolio();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.folioId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.parcelId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.registryId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.folioNumber = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.landDescription = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.extent = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.deedIds.push(reader.string());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.currentDeedId = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.updatedAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Folio {
    return {
      folioId: isSet(object.folioId) ? globalThis.String(object.folioId) : "",
      parcelId: isSet(object.parcelId) ? globalThis.String(object.parcelId) : "",
      registryId: isSet(object.registryId) ? globalThis.String(object.registryId) : "",
      folioNumber: isSet(object.folioNumber) ? globalThis.String(object.folioNumber) : "",
      landDescription: isSet(object.landDescription) ? globalThis.String(object.landDescription) : "",
      extent: isSet(object.extent) ? globalThis.String(object.extent) : "",
      deedIds: globalThis.Array.isArray(object?.deedIds) ? object.deedIds.map((e: any) => globalThis.String(e)) : [],
      currentDeedId: isSet(object.currentDeedId) ? globalThis.String(object.currentDeedId) : "",
      createdAt: isSet(object.createdAt) ? globalThis.String(object.createdAt) : "",
      updatedAt: isSet(object.updatedAt) ? globalThis.String(object.updatedAt) : "",
    };
  },

  toJSON(message: Folio): unknown {
    const obj: any = {};
    if (message.folioId !== "") {
      obj.folioId = message.folioId;
    }
    if (message.parcelId !== "") {
      obj.parcelId = message.parcelId;
    }
    if (message.registryId !== "") {
      obj.registryId = message.registryId;
    }
    if (message.folioNumber !== "") {
      obj.folioNumber = message.folioNumber;
    }
    if (message.landDescription !== "") {
      obj.landDescription = message.landDescription;
    }
    if (message.extent !== "") {
      obj.extent = message.extent;
    }
    if (message.deedIds?.length) {
      obj.deedIds = message.deedIds;
    }
    if (message.currentDeedId !== "") {
      obj.currentDeedId = message.currentDeedId;
    }
    if (message.createdAt !== "") {
      obj.createdAt = message.createdAt;
    }
    if (message.updatedAt !== "") {
      obj.updatedAt = message.updatedAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Folio>, I>>(base?: I): Folio {
    return Folio.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Folio>, I>>(object: I): Folio {
    const message = createBaseFolio();
    message.folioId = object.folioId ?? "";
    message.parcelId = object.parcelId ?? "";
    message.registryId = object.registryId ?? "";
    message.folioNumber = object.folioNumber ?? "";
    message.landDescription = object.landDescription ?? "";
    message.extent = object.extent ?? "";
    message.deedIds = object.deedIds?.map((e) => e) || [];
    message.currentDeedId = object.currentDeedId ?? "";
    message.createdAt = object.createdAt ?? "";
    message.updatedAt = object.updatedAt ?? "";
    return message;
  },
};

function createBaseStringArray(): StringArray {
  return { values: [] };
}

export const StringArray: MessageFns<StringArray> = {
  encode(message: StringArray, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.values) {
      writer.uint32(10).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StringArray {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStringArray();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.values.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StringArray {
    return {
      values: globalThis.Array.isArray(object?.values) ? object.values.map((e: any) => globalThis.String(e)) : [],
    };
  },

  toJSON(message: StringArray): unknown {
    const obj: any = {};
    if (message.values?.length) {
      obj.values = message.values;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StringArray>, I>>(base?: I): StringArray {
    return StringArray.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StringArray>, I>>(object: I): StringArray {
    const message = createBaseStringArray();
    message.values = object.values?.map((e) => e) || [];
    return message;
  },
};

function createBaseFolioRequest(): FolioRequest {
  return { requester: "", folioId: "", status: false, requestType: 0, createdAt: "", paid: false, remarks: "" };
}

export const FolioRequest: MessageFns<FolioRequest> = {
  encode(message: FolioRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requester !== "") {
      writer.uint32(10).string(message.requester);
    }
    if (message.folioId !== "") {
      writer.uint32(18).string(message.folioId);
    }
    if (message.status !== false) {
      writer.uint32(24).bool(message.status);
    }
    if (message.requestType !== 0) {
      writer.uint32(32).int32(message.requestType);
    }
    if (message.createdAt !== "") {
      writer.uint32(42).string(message.createdAt);
    }
    if (message.paid !== false) {
      writer.uint32(48).bool(message.paid);
    }
    if (message.remarks !== "") {
      writer.uint32(58).string(message.remarks);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FolioRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFolioRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.requester = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.folioId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.status = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.requestType = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.paid = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.remarks = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FolioRequest {
    return {
      requester: isSet(object.requester) ? globalThis.String(object.requester) : "",
      folioId: isSet(object.folioId) ? globalThis.String(object.folioId) : "",
      status: isSet(object.status) ? globalThis.Boolean(object.status) : false,
      requestType: isSet(object.requestType) ? requestTypeFromJSON(object.requestType) : 0,
      createdAt: isSet(object.createdAt) ? globalThis.String(object.createdAt) : "",
      paid: isSet(object.paid) ? globalThis.Boolean(object.paid) : false,
      remarks: isSet(object.remarks) ? globalThis.String(object.remarks) : "",
    };
  },

  toJSON(message: FolioRequest): unknown {
    const obj: any = {};
    if (message.requester !== "") {
      obj.requester = message.requester;
    }
    if (message.folioId !== "") {
      obj.folioId = message.folioId;
    }
    if (message.status !== false) {
      obj.status = message.status;
    }
    if (message.requestType !== 0) {
      obj.requestType = requestTypeToJSON(message.requestType);
    }
    if (message.createdAt !== "") {
      obj.createdAt = message.createdAt;
    }
    if (message.paid !== false) {
      obj.paid = message.paid;
    }
    if (message.remarks !== "") {
      obj.remarks = message.remarks;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FolioRequest>, I>>(base?: I): FolioRequest {
    return FolioRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FolioRequest>, I>>(object: I): FolioRequest {
    const message = createBaseFolioRequest();
    message.requester = object.requester ?? "";
    message.folioId = object.folioId ?? "";
    message.status = object.status ?? false;
    message.requestType = object.requestType ?? 0;
    message.createdAt = object.createdAt ?? "";
    message.paid = object.paid ?? false;
    message.remarks = object.remarks ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
