// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: elandnode/folio/v1/query.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { PageRequest, PageResponse } from "../../../cosmos/base/query/v1beta1/pagination";
import { Folio, FolioRequest } from "./folio";

export const protobufPackage = "elandnode.folio.v1";

export interface QueryPendingFolioRequestsRequest {
  requester: string;
  pagination: PageRequest | undefined;
}

export interface QueryPendingFolioRequestsResponse {
  status: string;
  code: number;
  message: string;
  folioRequests: FolioRequest[];
  requestId: string;
  timestamp: string;
  pagination: PageResponse | undefined;
}

export interface QueryFolioByIdOwnerOrNotaryRequest {
  folioId: string;
  creator: string;
}

/** Response message for getting folio by ID */
export interface QueryFolioByIdOwnerOrNotaryResponse {
  status: string;
  code: number;
  message: string;
  folio: Folio | undefined;
  requestId: string;
  timestamp: string;
}

export interface QueryFolioByIdRequest {
  folioId: string;
}

/** Response message for getting folio by ID */
export interface QueryFolioByIdResponse {
  status: string;
  code: number;
  message: string;
  folio: boolean;
  requestId: string;
  timestamp: string;
}

export interface QueryFolioByParcelRequest {
  parcelId: string;
}

export interface QueryFolioByParcelResponse {
  status: string;
  code: number;
  message: string;
  folio: Folio | undefined;
  requestId: string;
  timestamp: string;
}

export interface QueryFolioByDeedNumberRequest {
  deedNumber: string;
}

export interface QueryFolioByDeedNumberResponse {
  status: string;
  code: number;
  message: string;
  folio: Folio | undefined;
  requestId: string;
  timestamp: string;
}

export interface QueryFolioByOwnerNICRequest {
  nic: string;
}

export interface QueryFolioByOwnerNICResponse {
  status: string;
  code: number;
  message: string;
  folios: Folio[];
  requestId: string;
  timestamp: string;
}

function createBaseQueryPendingFolioRequestsRequest(): QueryPendingFolioRequestsRequest {
  return { requester: "", pagination: undefined };
}

export const QueryPendingFolioRequestsRequest: MessageFns<QueryPendingFolioRequestsRequest> = {
  encode(message: QueryPendingFolioRequestsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requester !== "") {
      writer.uint32(10).string(message.requester);
    }
    if (message.pagination !== undefined) {
      PageRequest.encode(message.pagination, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryPendingFolioRequestsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryPendingFolioRequestsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.requester = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pagination = PageRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryPendingFolioRequestsRequest {
    return {
      requester: isSet(object.requester) ? globalThis.String(object.requester) : "",
      pagination: isSet(object.pagination) ? PageRequest.fromJSON(object.pagination) : undefined,
    };
  },

  toJSON(message: QueryPendingFolioRequestsRequest): unknown {
    const obj: any = {};
    if (message.requester !== "") {
      obj.requester = message.requester;
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageRequest.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryPendingFolioRequestsRequest>, I>>(
    base?: I,
  ): QueryPendingFolioRequestsRequest {
    return QueryPendingFolioRequestsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryPendingFolioRequestsRequest>, I>>(
    object: I,
  ): QueryPendingFolioRequestsRequest {
    const message = createBaseQueryPendingFolioRequestsRequest();
    message.requester = object.requester ?? "";
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageRequest.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseQueryPendingFolioRequestsResponse(): QueryPendingFolioRequestsResponse {
  return { status: "", code: 0, message: "", folioRequests: [], requestId: "", timestamp: "", pagination: undefined };
}

export const QueryPendingFolioRequestsResponse: MessageFns<QueryPendingFolioRequestsResponse> = {
  encode(message: QueryPendingFolioRequestsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.code !== 0) {
      writer.uint32(16).int32(message.code);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    for (const v of message.folioRequests) {
      FolioRequest.encode(v!, writer.uint32(34).fork()).join();
    }
    if (message.requestId !== "") {
      writer.uint32(42).string(message.requestId);
    }
    if (message.timestamp !== "") {
      writer.uint32(50).string(message.timestamp);
    }
    if (message.pagination !== undefined) {
      PageResponse.encode(message.pagination, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryPendingFolioRequestsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryPendingFolioRequestsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.code = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.folioRequests.push(FolioRequest.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.pagination = PageResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryPendingFolioRequestsResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      folioRequests: globalThis.Array.isArray(object?.folioRequests)
        ? object.folioRequests.map((e: any) => FolioRequest.fromJSON(e))
        : [],
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
      pagination: isSet(object.pagination) ? PageResponse.fromJSON(object.pagination) : undefined,
    };
  },

  toJSON(message: QueryPendingFolioRequestsResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.folioRequests?.length) {
      obj.folioRequests = message.folioRequests.map((e) => FolioRequest.toJSON(e));
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.timestamp !== "") {
      obj.timestamp = message.timestamp;
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageResponse.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryPendingFolioRequestsResponse>, I>>(
    base?: I,
  ): QueryPendingFolioRequestsResponse {
    return QueryPendingFolioRequestsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryPendingFolioRequestsResponse>, I>>(
    object: I,
  ): QueryPendingFolioRequestsResponse {
    const message = createBaseQueryPendingFolioRequestsResponse();
    message.status = object.status ?? "";
    message.code = object.code ?? 0;
    message.message = object.message ?? "";
    message.folioRequests = object.folioRequests?.map((e) => FolioRequest.fromPartial(e)) || [];
    message.requestId = object.requestId ?? "";
    message.timestamp = object.timestamp ?? "";
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageResponse.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseQueryFolioByIdOwnerOrNotaryRequest(): QueryFolioByIdOwnerOrNotaryRequest {
  return { folioId: "", creator: "" };
}

export const QueryFolioByIdOwnerOrNotaryRequest: MessageFns<QueryFolioByIdOwnerOrNotaryRequest> = {
  encode(message: QueryFolioByIdOwnerOrNotaryRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.folioId !== "") {
      writer.uint32(10).string(message.folioId);
    }
    if (message.creator !== "") {
      writer.uint32(18).string(message.creator);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryFolioByIdOwnerOrNotaryRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryFolioByIdOwnerOrNotaryRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.folioId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryFolioByIdOwnerOrNotaryRequest {
    return {
      folioId: isSet(object.folioId) ? globalThis.String(object.folioId) : "",
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
    };
  },

  toJSON(message: QueryFolioByIdOwnerOrNotaryRequest): unknown {
    const obj: any = {};
    if (message.folioId !== "") {
      obj.folioId = message.folioId;
    }
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryFolioByIdOwnerOrNotaryRequest>, I>>(
    base?: I,
  ): QueryFolioByIdOwnerOrNotaryRequest {
    return QueryFolioByIdOwnerOrNotaryRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryFolioByIdOwnerOrNotaryRequest>, I>>(
    object: I,
  ): QueryFolioByIdOwnerOrNotaryRequest {
    const message = createBaseQueryFolioByIdOwnerOrNotaryRequest();
    message.folioId = object.folioId ?? "";
    message.creator = object.creator ?? "";
    return message;
  },
};

function createBaseQueryFolioByIdOwnerOrNotaryResponse(): QueryFolioByIdOwnerOrNotaryResponse {
  return { status: "", code: 0, message: "", folio: undefined, requestId: "", timestamp: "" };
}

export const QueryFolioByIdOwnerOrNotaryResponse: MessageFns<QueryFolioByIdOwnerOrNotaryResponse> = {
  encode(message: QueryFolioByIdOwnerOrNotaryResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.code !== 0) {
      writer.uint32(16).int32(message.code);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    if (message.folio !== undefined) {
      Folio.encode(message.folio, writer.uint32(34).fork()).join();
    }
    if (message.requestId !== "") {
      writer.uint32(42).string(message.requestId);
    }
    if (message.timestamp !== "") {
      writer.uint32(50).string(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryFolioByIdOwnerOrNotaryResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryFolioByIdOwnerOrNotaryResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.code = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.folio = Folio.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryFolioByIdOwnerOrNotaryResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      folio: isSet(object.folio) ? Folio.fromJSON(object.folio) : undefined,
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
    };
  },

  toJSON(message: QueryFolioByIdOwnerOrNotaryResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.folio !== undefined) {
      obj.folio = Folio.toJSON(message.folio);
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.timestamp !== "") {
      obj.timestamp = message.timestamp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryFolioByIdOwnerOrNotaryResponse>, I>>(
    base?: I,
  ): QueryFolioByIdOwnerOrNotaryResponse {
    return QueryFolioByIdOwnerOrNotaryResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryFolioByIdOwnerOrNotaryResponse>, I>>(
    object: I,
  ): QueryFolioByIdOwnerOrNotaryResponse {
    const message = createBaseQueryFolioByIdOwnerOrNotaryResponse();
    message.status = object.status ?? "";
    message.code = object.code ?? 0;
    message.message = object.message ?? "";
    message.folio = (object.folio !== undefined && object.folio !== null) ? Folio.fromPartial(object.folio) : undefined;
    message.requestId = object.requestId ?? "";
    message.timestamp = object.timestamp ?? "";
    return message;
  },
};

function createBaseQueryFolioByIdRequest(): QueryFolioByIdRequest {
  return { folioId: "" };
}

export const QueryFolioByIdRequest: MessageFns<QueryFolioByIdRequest> = {
  encode(message: QueryFolioByIdRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.folioId !== "") {
      writer.uint32(10).string(message.folioId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryFolioByIdRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryFolioByIdRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.folioId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryFolioByIdRequest {
    return { folioId: isSet(object.folioId) ? globalThis.String(object.folioId) : "" };
  },

  toJSON(message: QueryFolioByIdRequest): unknown {
    const obj: any = {};
    if (message.folioId !== "") {
      obj.folioId = message.folioId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryFolioByIdRequest>, I>>(base?: I): QueryFolioByIdRequest {
    return QueryFolioByIdRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryFolioByIdRequest>, I>>(object: I): QueryFolioByIdRequest {
    const message = createBaseQueryFolioByIdRequest();
    message.folioId = object.folioId ?? "";
    return message;
  },
};

function createBaseQueryFolioByIdResponse(): QueryFolioByIdResponse {
  return { status: "", code: 0, message: "", folio: false, requestId: "", timestamp: "" };
}

export const QueryFolioByIdResponse: MessageFns<QueryFolioByIdResponse> = {
  encode(message: QueryFolioByIdResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.code !== 0) {
      writer.uint32(16).int32(message.code);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    if (message.folio !== false) {
      writer.uint32(32).bool(message.folio);
    }
    if (message.requestId !== "") {
      writer.uint32(42).string(message.requestId);
    }
    if (message.timestamp !== "") {
      writer.uint32(50).string(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryFolioByIdResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryFolioByIdResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.code = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.folio = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryFolioByIdResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      folio: isSet(object.folio) ? globalThis.Boolean(object.folio) : false,
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
    };
  },

  toJSON(message: QueryFolioByIdResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.folio !== false) {
      obj.folio = message.folio;
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.timestamp !== "") {
      obj.timestamp = message.timestamp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryFolioByIdResponse>, I>>(base?: I): QueryFolioByIdResponse {
    return QueryFolioByIdResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryFolioByIdResponse>, I>>(object: I): QueryFolioByIdResponse {
    const message = createBaseQueryFolioByIdResponse();
    message.status = object.status ?? "";
    message.code = object.code ?? 0;
    message.message = object.message ?? "";
    message.folio = object.folio ?? false;
    message.requestId = object.requestId ?? "";
    message.timestamp = object.timestamp ?? "";
    return message;
  },
};

function createBaseQueryFolioByParcelRequest(): QueryFolioByParcelRequest {
  return { parcelId: "" };
}

export const QueryFolioByParcelRequest: MessageFns<QueryFolioByParcelRequest> = {
  encode(message: QueryFolioByParcelRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.parcelId !== "") {
      writer.uint32(10).string(message.parcelId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryFolioByParcelRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryFolioByParcelRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.parcelId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryFolioByParcelRequest {
    return { parcelId: isSet(object.parcelId) ? globalThis.String(object.parcelId) : "" };
  },

  toJSON(message: QueryFolioByParcelRequest): unknown {
    const obj: any = {};
    if (message.parcelId !== "") {
      obj.parcelId = message.parcelId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryFolioByParcelRequest>, I>>(base?: I): QueryFolioByParcelRequest {
    return QueryFolioByParcelRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryFolioByParcelRequest>, I>>(object: I): QueryFolioByParcelRequest {
    const message = createBaseQueryFolioByParcelRequest();
    message.parcelId = object.parcelId ?? "";
    return message;
  },
};

function createBaseQueryFolioByParcelResponse(): QueryFolioByParcelResponse {
  return { status: "", code: 0, message: "", folio: undefined, requestId: "", timestamp: "" };
}

export const QueryFolioByParcelResponse: MessageFns<QueryFolioByParcelResponse> = {
  encode(message: QueryFolioByParcelResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.code !== 0) {
      writer.uint32(16).int32(message.code);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    if (message.folio !== undefined) {
      Folio.encode(message.folio, writer.uint32(34).fork()).join();
    }
    if (message.requestId !== "") {
      writer.uint32(42).string(message.requestId);
    }
    if (message.timestamp !== "") {
      writer.uint32(50).string(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryFolioByParcelResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryFolioByParcelResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.code = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.folio = Folio.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryFolioByParcelResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      folio: isSet(object.folio) ? Folio.fromJSON(object.folio) : undefined,
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
    };
  },

  toJSON(message: QueryFolioByParcelResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.folio !== undefined) {
      obj.folio = Folio.toJSON(message.folio);
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.timestamp !== "") {
      obj.timestamp = message.timestamp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryFolioByParcelResponse>, I>>(base?: I): QueryFolioByParcelResponse {
    return QueryFolioByParcelResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryFolioByParcelResponse>, I>>(object: I): QueryFolioByParcelResponse {
    const message = createBaseQueryFolioByParcelResponse();
    message.status = object.status ?? "";
    message.code = object.code ?? 0;
    message.message = object.message ?? "";
    message.folio = (object.folio !== undefined && object.folio !== null) ? Folio.fromPartial(object.folio) : undefined;
    message.requestId = object.requestId ?? "";
    message.timestamp = object.timestamp ?? "";
    return message;
  },
};

function createBaseQueryFolioByDeedNumberRequest(): QueryFolioByDeedNumberRequest {
  return { deedNumber: "" };
}

export const QueryFolioByDeedNumberRequest: MessageFns<QueryFolioByDeedNumberRequest> = {
  encode(message: QueryFolioByDeedNumberRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.deedNumber !== "") {
      writer.uint32(10).string(message.deedNumber);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryFolioByDeedNumberRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryFolioByDeedNumberRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.deedNumber = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryFolioByDeedNumberRequest {
    return { deedNumber: isSet(object.deedNumber) ? globalThis.String(object.deedNumber) : "" };
  },

  toJSON(message: QueryFolioByDeedNumberRequest): unknown {
    const obj: any = {};
    if (message.deedNumber !== "") {
      obj.deedNumber = message.deedNumber;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryFolioByDeedNumberRequest>, I>>(base?: I): QueryFolioByDeedNumberRequest {
    return QueryFolioByDeedNumberRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryFolioByDeedNumberRequest>, I>>(
    object: I,
  ): QueryFolioByDeedNumberRequest {
    const message = createBaseQueryFolioByDeedNumberRequest();
    message.deedNumber = object.deedNumber ?? "";
    return message;
  },
};

function createBaseQueryFolioByDeedNumberResponse(): QueryFolioByDeedNumberResponse {
  return { status: "", code: 0, message: "", folio: undefined, requestId: "", timestamp: "" };
}

export const QueryFolioByDeedNumberResponse: MessageFns<QueryFolioByDeedNumberResponse> = {
  encode(message: QueryFolioByDeedNumberResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.code !== 0) {
      writer.uint32(16).int32(message.code);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    if (message.folio !== undefined) {
      Folio.encode(message.folio, writer.uint32(34).fork()).join();
    }
    if (message.requestId !== "") {
      writer.uint32(42).string(message.requestId);
    }
    if (message.timestamp !== "") {
      writer.uint32(50).string(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryFolioByDeedNumberResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryFolioByDeedNumberResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.code = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.folio = Folio.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryFolioByDeedNumberResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      folio: isSet(object.folio) ? Folio.fromJSON(object.folio) : undefined,
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
    };
  },

  toJSON(message: QueryFolioByDeedNumberResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.folio !== undefined) {
      obj.folio = Folio.toJSON(message.folio);
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.timestamp !== "") {
      obj.timestamp = message.timestamp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryFolioByDeedNumberResponse>, I>>(base?: I): QueryFolioByDeedNumberResponse {
    return QueryFolioByDeedNumberResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryFolioByDeedNumberResponse>, I>>(
    object: I,
  ): QueryFolioByDeedNumberResponse {
    const message = createBaseQueryFolioByDeedNumberResponse();
    message.status = object.status ?? "";
    message.code = object.code ?? 0;
    message.message = object.message ?? "";
    message.folio = (object.folio !== undefined && object.folio !== null) ? Folio.fromPartial(object.folio) : undefined;
    message.requestId = object.requestId ?? "";
    message.timestamp = object.timestamp ?? "";
    return message;
  },
};

function createBaseQueryFolioByOwnerNICRequest(): QueryFolioByOwnerNICRequest {
  return { nic: "" };
}

export const QueryFolioByOwnerNICRequest: MessageFns<QueryFolioByOwnerNICRequest> = {
  encode(message: QueryFolioByOwnerNICRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.nic !== "") {
      writer.uint32(10).string(message.nic);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryFolioByOwnerNICRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryFolioByOwnerNICRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.nic = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryFolioByOwnerNICRequest {
    return { nic: isSet(object.nic) ? globalThis.String(object.nic) : "" };
  },

  toJSON(message: QueryFolioByOwnerNICRequest): unknown {
    const obj: any = {};
    if (message.nic !== "") {
      obj.nic = message.nic;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryFolioByOwnerNICRequest>, I>>(base?: I): QueryFolioByOwnerNICRequest {
    return QueryFolioByOwnerNICRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryFolioByOwnerNICRequest>, I>>(object: I): QueryFolioByOwnerNICRequest {
    const message = createBaseQueryFolioByOwnerNICRequest();
    message.nic = object.nic ?? "";
    return message;
  },
};

function createBaseQueryFolioByOwnerNICResponse(): QueryFolioByOwnerNICResponse {
  return { status: "", code: 0, message: "", folios: [], requestId: "", timestamp: "" };
}

export const QueryFolioByOwnerNICResponse: MessageFns<QueryFolioByOwnerNICResponse> = {
  encode(message: QueryFolioByOwnerNICResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.code !== 0) {
      writer.uint32(16).int32(message.code);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    for (const v of message.folios) {
      Folio.encode(v!, writer.uint32(34).fork()).join();
    }
    if (message.requestId !== "") {
      writer.uint32(42).string(message.requestId);
    }
    if (message.timestamp !== "") {
      writer.uint32(50).string(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryFolioByOwnerNICResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryFolioByOwnerNICResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.code = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.folios.push(Folio.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryFolioByOwnerNICResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      folios: globalThis.Array.isArray(object?.folios) ? object.folios.map((e: any) => Folio.fromJSON(e)) : [],
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
    };
  },

  toJSON(message: QueryFolioByOwnerNICResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.folios?.length) {
      obj.folios = message.folios.map((e) => Folio.toJSON(e));
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.timestamp !== "") {
      obj.timestamp = message.timestamp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryFolioByOwnerNICResponse>, I>>(base?: I): QueryFolioByOwnerNICResponse {
    return QueryFolioByOwnerNICResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryFolioByOwnerNICResponse>, I>>(object: I): QueryFolioByOwnerNICResponse {
    const message = createBaseQueryFolioByOwnerNICResponse();
    message.status = object.status ?? "";
    message.code = object.code ?? 0;
    message.message = object.message ?? "";
    message.folios = object.folios?.map((e) => Folio.fromPartial(e)) || [];
    message.requestId = object.requestId ?? "";
    message.timestamp = object.timestamp ?? "";
    return message;
  },
};

/** Query defines the gRPC querier service. */
export interface Query {
  /**
   * FolioByParcel returns the folio record associated with a given parcel ID.
   * This allows registry officers or survey departments to quickly locate folio data
   * that corresponds to a specific land parcel.
   */
  FolioByParcel(request: QueryFolioByParcelRequest): Promise<QueryFolioByParcelResponse>;
  /**
   * FolioByDeedNumber returns the folio details linked to a specific deed number.
   * Useful for tracing ownership and registration chains between deeds and folios.
   */
  FolioByDeedNumber(request: QueryFolioByDeedNumberRequest): Promise<QueryFolioByDeedNumberResponse>;
  /**
   * FolioByOwnerNIC returns all folio records associated with a particular owner's NIC.
   * Typically used to retrieve a list of properties owned by a citizen or entity.
   */
  FolioByOwnerNIC(request: QueryFolioByOwnerNICRequest): Promise<QueryFolioByOwnerNICResponse>;
  /**
   * FolioById retrieves a single folio by its unique folio ID.
   * Provides boolean  information about requested folio.
   */
  FolioById(request: QueryFolioByIdRequest): Promise<QueryFolioByIdResponse>;
  /**
   * FolioByIdOwnerOrNotary retrieves a folio by ID only if the caller is either the registered owner
   * or an authorized notary. This enforces access control to sensitive land registration data.by ensureing aproval before data retrival
   */
  FolioByIdOwnerOrNotary(request: QueryFolioByIdOwnerOrNotaryRequest): Promise<QueryFolioByIdOwnerOrNotaryResponse>;
  /**
   * PendingFolioRequests returns all folio requests that are awaiting approval.
   * Typically accessed by registry officers for review and approval workflows.
   */
  PendingFolioRequests(request: QueryPendingFolioRequestsRequest): Promise<QueryPendingFolioRequestsResponse>;
}

export const QueryServiceName = "elandnode.folio.v1.Query";
export class QueryClientImpl implements Query {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || QueryServiceName;
    this.rpc = rpc;
    this.FolioByParcel = this.FolioByParcel.bind(this);
    this.FolioByDeedNumber = this.FolioByDeedNumber.bind(this);
    this.FolioByOwnerNIC = this.FolioByOwnerNIC.bind(this);
    this.FolioById = this.FolioById.bind(this);
    this.FolioByIdOwnerOrNotary = this.FolioByIdOwnerOrNotary.bind(this);
    this.PendingFolioRequests = this.PendingFolioRequests.bind(this);
  }
  FolioByParcel(request: QueryFolioByParcelRequest): Promise<QueryFolioByParcelResponse> {
    const data = QueryFolioByParcelRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "FolioByParcel", data);
    return promise.then((data) => QueryFolioByParcelResponse.decode(new BinaryReader(data)));
  }

  FolioByDeedNumber(request: QueryFolioByDeedNumberRequest): Promise<QueryFolioByDeedNumberResponse> {
    const data = QueryFolioByDeedNumberRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "FolioByDeedNumber", data);
    return promise.then((data) => QueryFolioByDeedNumberResponse.decode(new BinaryReader(data)));
  }

  FolioByOwnerNIC(request: QueryFolioByOwnerNICRequest): Promise<QueryFolioByOwnerNICResponse> {
    const data = QueryFolioByOwnerNICRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "FolioByOwnerNIC", data);
    return promise.then((data) => QueryFolioByOwnerNICResponse.decode(new BinaryReader(data)));
  }

  FolioById(request: QueryFolioByIdRequest): Promise<QueryFolioByIdResponse> {
    const data = QueryFolioByIdRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "FolioById", data);
    return promise.then((data) => QueryFolioByIdResponse.decode(new BinaryReader(data)));
  }

  FolioByIdOwnerOrNotary(request: QueryFolioByIdOwnerOrNotaryRequest): Promise<QueryFolioByIdOwnerOrNotaryResponse> {
    const data = QueryFolioByIdOwnerOrNotaryRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "FolioByIdOwnerOrNotary", data);
    return promise.then((data) => QueryFolioByIdOwnerOrNotaryResponse.decode(new BinaryReader(data)));
  }

  PendingFolioRequests(request: QueryPendingFolioRequestsRequest): Promise<QueryPendingFolioRequestsResponse> {
    const data = QueryPendingFolioRequestsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "PendingFolioRequests", data);
    return promise.then((data) => QueryPendingFolioRequestsResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
