// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: elandnode/folio/v1/tx.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { RequestType, requestTypeFromJSON, requestTypeToJSON } from "./folio";

export const protobufPackage = "elandnode.folio.v1";

export interface MsgApproveFolioRequest {
  creator: string;
  decision: boolean;
  folioId: string;
  remarks: string;
}

export interface MsgApproveFolioRequestResponse {
  status: string;
  code: number;
  message: string;
  data: string;
  requestId: string;
  timestamp: string;
}

export interface MsgRequestFolio {
  creator: string;
  folioId: string;
  requestType: RequestType;
}

export interface MsgRequestFolioResponse {
  status: string;
  code: number;
  message: string;
  data: string;
  requestId: string;
  timestamp: string;
}

export interface MsgSubmitNotarySignature {
  creator: string;
  folioId: string;
  deedNumber: string;
  notaryNic: string;
  notarySignature: string;
  signatureTimestamp: string;
}

export interface SubmitNotary {
  folioId: string;
  deedNumber: string;
  signatureAttached: boolean;
}

export interface MsgSubmitNotarySignatureResponse {
  status: string;
  code: number;
  message: string;
  data: SubmitNotary | undefined;
  requestId: string;
  timestamp: string;
}

export interface MsgCreateFolio {
  registrar: string;
  folioId: string;
  parcelId: string;
  registryId: string;
  folioNumber: string;
  landDescription: string;
  extent: string;
  creator: string;
}

export interface MsgCreateFolioResponse {
  status: string;
  code: number;
  message: string;
  data: string;
  requestId: string;
  timestamp: string;
}

export interface MsgRegisterDeedInFolio {
  registrarId: string;
  folioId: string;
  deedId: string;
  creator: string;
}

export interface MsgRegisterDeedInFolioResponse {
  status: string;
  code: number;
  message: string;
  data: string;
  requestId: string;
  timestamp: string;
}

function createBaseMsgApproveFolioRequest(): MsgApproveFolioRequest {
  return { creator: "", decision: false, folioId: "", remarks: "" };
}

export const MsgApproveFolioRequest: MessageFns<MsgApproveFolioRequest> = {
  encode(message: MsgApproveFolioRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.decision !== false) {
      writer.uint32(16).bool(message.decision);
    }
    if (message.folioId !== "") {
      writer.uint32(26).string(message.folioId);
    }
    if (message.remarks !== "") {
      writer.uint32(34).string(message.remarks);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgApproveFolioRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgApproveFolioRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.decision = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.folioId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.remarks = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgApproveFolioRequest {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      decision: isSet(object.decision) ? globalThis.Boolean(object.decision) : false,
      folioId: isSet(object.folioId) ? globalThis.String(object.folioId) : "",
      remarks: isSet(object.remarks) ? globalThis.String(object.remarks) : "",
    };
  },

  toJSON(message: MsgApproveFolioRequest): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.decision !== false) {
      obj.decision = message.decision;
    }
    if (message.folioId !== "") {
      obj.folioId = message.folioId;
    }
    if (message.remarks !== "") {
      obj.remarks = message.remarks;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgApproveFolioRequest>, I>>(base?: I): MsgApproveFolioRequest {
    return MsgApproveFolioRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgApproveFolioRequest>, I>>(object: I): MsgApproveFolioRequest {
    const message = createBaseMsgApproveFolioRequest();
    message.creator = object.creator ?? "";
    message.decision = object.decision ?? false;
    message.folioId = object.folioId ?? "";
    message.remarks = object.remarks ?? "";
    return message;
  },
};

function createBaseMsgApproveFolioRequestResponse(): MsgApproveFolioRequestResponse {
  return { status: "", code: 0, message: "", data: "", requestId: "", timestamp: "" };
}

export const MsgApproveFolioRequestResponse: MessageFns<MsgApproveFolioRequestResponse> = {
  encode(message: MsgApproveFolioRequestResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.code !== 0) {
      writer.uint32(16).int32(message.code);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    if (message.data !== "") {
      writer.uint32(34).string(message.data);
    }
    if (message.requestId !== "") {
      writer.uint32(42).string(message.requestId);
    }
    if (message.timestamp !== "") {
      writer.uint32(50).string(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgApproveFolioRequestResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgApproveFolioRequestResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.code = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.data = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgApproveFolioRequestResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      data: isSet(object.data) ? globalThis.String(object.data) : "",
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
    };
  },

  toJSON(message: MsgApproveFolioRequestResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.data !== "") {
      obj.data = message.data;
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.timestamp !== "") {
      obj.timestamp = message.timestamp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgApproveFolioRequestResponse>, I>>(base?: I): MsgApproveFolioRequestResponse {
    return MsgApproveFolioRequestResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgApproveFolioRequestResponse>, I>>(
    object: I,
  ): MsgApproveFolioRequestResponse {
    const message = createBaseMsgApproveFolioRequestResponse();
    message.status = object.status ?? "";
    message.code = object.code ?? 0;
    message.message = object.message ?? "";
    message.data = object.data ?? "";
    message.requestId = object.requestId ?? "";
    message.timestamp = object.timestamp ?? "";
    return message;
  },
};

function createBaseMsgRequestFolio(): MsgRequestFolio {
  return { creator: "", folioId: "", requestType: 0 };
}

export const MsgRequestFolio: MessageFns<MsgRequestFolio> = {
  encode(message: MsgRequestFolio, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.folioId !== "") {
      writer.uint32(18).string(message.folioId);
    }
    if (message.requestType !== 0) {
      writer.uint32(24).int32(message.requestType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRequestFolio {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgRequestFolio();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.folioId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.requestType = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgRequestFolio {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      folioId: isSet(object.folioId) ? globalThis.String(object.folioId) : "",
      requestType: isSet(object.requestType) ? requestTypeFromJSON(object.requestType) : 0,
    };
  },

  toJSON(message: MsgRequestFolio): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.folioId !== "") {
      obj.folioId = message.folioId;
    }
    if (message.requestType !== 0) {
      obj.requestType = requestTypeToJSON(message.requestType);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRequestFolio>, I>>(base?: I): MsgRequestFolio {
    return MsgRequestFolio.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRequestFolio>, I>>(object: I): MsgRequestFolio {
    const message = createBaseMsgRequestFolio();
    message.creator = object.creator ?? "";
    message.folioId = object.folioId ?? "";
    message.requestType = object.requestType ?? 0;
    return message;
  },
};

function createBaseMsgRequestFolioResponse(): MsgRequestFolioResponse {
  return { status: "", code: 0, message: "", data: "", requestId: "", timestamp: "" };
}

export const MsgRequestFolioResponse: MessageFns<MsgRequestFolioResponse> = {
  encode(message: MsgRequestFolioResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.code !== 0) {
      writer.uint32(16).int32(message.code);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    if (message.data !== "") {
      writer.uint32(34).string(message.data);
    }
    if (message.requestId !== "") {
      writer.uint32(42).string(message.requestId);
    }
    if (message.timestamp !== "") {
      writer.uint32(50).string(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRequestFolioResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgRequestFolioResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.code = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.data = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgRequestFolioResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      data: isSet(object.data) ? globalThis.String(object.data) : "",
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
    };
  },

  toJSON(message: MsgRequestFolioResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.data !== "") {
      obj.data = message.data;
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.timestamp !== "") {
      obj.timestamp = message.timestamp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRequestFolioResponse>, I>>(base?: I): MsgRequestFolioResponse {
    return MsgRequestFolioResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRequestFolioResponse>, I>>(object: I): MsgRequestFolioResponse {
    const message = createBaseMsgRequestFolioResponse();
    message.status = object.status ?? "";
    message.code = object.code ?? 0;
    message.message = object.message ?? "";
    message.data = object.data ?? "";
    message.requestId = object.requestId ?? "";
    message.timestamp = object.timestamp ?? "";
    return message;
  },
};

function createBaseMsgSubmitNotarySignature(): MsgSubmitNotarySignature {
  return { creator: "", folioId: "", deedNumber: "", notaryNic: "", notarySignature: "", signatureTimestamp: "" };
}

export const MsgSubmitNotarySignature: MessageFns<MsgSubmitNotarySignature> = {
  encode(message: MsgSubmitNotarySignature, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.folioId !== "") {
      writer.uint32(18).string(message.folioId);
    }
    if (message.deedNumber !== "") {
      writer.uint32(26).string(message.deedNumber);
    }
    if (message.notaryNic !== "") {
      writer.uint32(34).string(message.notaryNic);
    }
    if (message.notarySignature !== "") {
      writer.uint32(42).string(message.notarySignature);
    }
    if (message.signatureTimestamp !== "") {
      writer.uint32(50).string(message.signatureTimestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSubmitNotarySignature {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSubmitNotarySignature();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.folioId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.deedNumber = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.notaryNic = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.notarySignature = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.signatureTimestamp = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgSubmitNotarySignature {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      folioId: isSet(object.folioId) ? globalThis.String(object.folioId) : "",
      deedNumber: isSet(object.deedNumber) ? globalThis.String(object.deedNumber) : "",
      notaryNic: isSet(object.notaryNic) ? globalThis.String(object.notaryNic) : "",
      notarySignature: isSet(object.notarySignature) ? globalThis.String(object.notarySignature) : "",
      signatureTimestamp: isSet(object.signatureTimestamp) ? globalThis.String(object.signatureTimestamp) : "",
    };
  },

  toJSON(message: MsgSubmitNotarySignature): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.folioId !== "") {
      obj.folioId = message.folioId;
    }
    if (message.deedNumber !== "") {
      obj.deedNumber = message.deedNumber;
    }
    if (message.notaryNic !== "") {
      obj.notaryNic = message.notaryNic;
    }
    if (message.notarySignature !== "") {
      obj.notarySignature = message.notarySignature;
    }
    if (message.signatureTimestamp !== "") {
      obj.signatureTimestamp = message.signatureTimestamp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSubmitNotarySignature>, I>>(base?: I): MsgSubmitNotarySignature {
    return MsgSubmitNotarySignature.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSubmitNotarySignature>, I>>(object: I): MsgSubmitNotarySignature {
    const message = createBaseMsgSubmitNotarySignature();
    message.creator = object.creator ?? "";
    message.folioId = object.folioId ?? "";
    message.deedNumber = object.deedNumber ?? "";
    message.notaryNic = object.notaryNic ?? "";
    message.notarySignature = object.notarySignature ?? "";
    message.signatureTimestamp = object.signatureTimestamp ?? "";
    return message;
  },
};

function createBaseSubmitNotary(): SubmitNotary {
  return { folioId: "", deedNumber: "", signatureAttached: false };
}

export const SubmitNotary: MessageFns<SubmitNotary> = {
  encode(message: SubmitNotary, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.folioId !== "") {
      writer.uint32(10).string(message.folioId);
    }
    if (message.deedNumber !== "") {
      writer.uint32(18).string(message.deedNumber);
    }
    if (message.signatureAttached !== false) {
      writer.uint32(24).bool(message.signatureAttached);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SubmitNotary {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubmitNotary();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.folioId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.deedNumber = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.signatureAttached = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SubmitNotary {
    return {
      folioId: isSet(object.folioId) ? globalThis.String(object.folioId) : "",
      deedNumber: isSet(object.deedNumber) ? globalThis.String(object.deedNumber) : "",
      signatureAttached: isSet(object.signatureAttached) ? globalThis.Boolean(object.signatureAttached) : false,
    };
  },

  toJSON(message: SubmitNotary): unknown {
    const obj: any = {};
    if (message.folioId !== "") {
      obj.folioId = message.folioId;
    }
    if (message.deedNumber !== "") {
      obj.deedNumber = message.deedNumber;
    }
    if (message.signatureAttached !== false) {
      obj.signatureAttached = message.signatureAttached;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SubmitNotary>, I>>(base?: I): SubmitNotary {
    return SubmitNotary.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SubmitNotary>, I>>(object: I): SubmitNotary {
    const message = createBaseSubmitNotary();
    message.folioId = object.folioId ?? "";
    message.deedNumber = object.deedNumber ?? "";
    message.signatureAttached = object.signatureAttached ?? false;
    return message;
  },
};

function createBaseMsgSubmitNotarySignatureResponse(): MsgSubmitNotarySignatureResponse {
  return { status: "", code: 0, message: "", data: undefined, requestId: "", timestamp: "" };
}

export const MsgSubmitNotarySignatureResponse: MessageFns<MsgSubmitNotarySignatureResponse> = {
  encode(message: MsgSubmitNotarySignatureResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.code !== 0) {
      writer.uint32(16).int32(message.code);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    if (message.data !== undefined) {
      SubmitNotary.encode(message.data, writer.uint32(34).fork()).join();
    }
    if (message.requestId !== "") {
      writer.uint32(42).string(message.requestId);
    }
    if (message.timestamp !== "") {
      writer.uint32(50).string(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSubmitNotarySignatureResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSubmitNotarySignatureResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.code = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.data = SubmitNotary.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgSubmitNotarySignatureResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      data: isSet(object.data) ? SubmitNotary.fromJSON(object.data) : undefined,
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
    };
  },

  toJSON(message: MsgSubmitNotarySignatureResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.data !== undefined) {
      obj.data = SubmitNotary.toJSON(message.data);
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.timestamp !== "") {
      obj.timestamp = message.timestamp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSubmitNotarySignatureResponse>, I>>(
    base?: I,
  ): MsgSubmitNotarySignatureResponse {
    return MsgSubmitNotarySignatureResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSubmitNotarySignatureResponse>, I>>(
    object: I,
  ): MsgSubmitNotarySignatureResponse {
    const message = createBaseMsgSubmitNotarySignatureResponse();
    message.status = object.status ?? "";
    message.code = object.code ?? 0;
    message.message = object.message ?? "";
    message.data = (object.data !== undefined && object.data !== null)
      ? SubmitNotary.fromPartial(object.data)
      : undefined;
    message.requestId = object.requestId ?? "";
    message.timestamp = object.timestamp ?? "";
    return message;
  },
};

function createBaseMsgCreateFolio(): MsgCreateFolio {
  return {
    registrar: "",
    folioId: "",
    parcelId: "",
    registryId: "",
    folioNumber: "",
    landDescription: "",
    extent: "",
    creator: "",
  };
}

export const MsgCreateFolio: MessageFns<MsgCreateFolio> = {
  encode(message: MsgCreateFolio, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.registrar !== "") {
      writer.uint32(10).string(message.registrar);
    }
    if (message.folioId !== "") {
      writer.uint32(18).string(message.folioId);
    }
    if (message.parcelId !== "") {
      writer.uint32(26).string(message.parcelId);
    }
    if (message.registryId !== "") {
      writer.uint32(34).string(message.registryId);
    }
    if (message.folioNumber !== "") {
      writer.uint32(42).string(message.folioNumber);
    }
    if (message.landDescription !== "") {
      writer.uint32(50).string(message.landDescription);
    }
    if (message.extent !== "") {
      writer.uint32(58).string(message.extent);
    }
    if (message.creator !== "") {
      writer.uint32(66).string(message.creator);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCreateFolio {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCreateFolio();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.registrar = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.folioId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.parcelId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.registryId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.folioNumber = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.landDescription = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.extent = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgCreateFolio {
    return {
      registrar: isSet(object.registrar) ? globalThis.String(object.registrar) : "",
      folioId: isSet(object.folioId) ? globalThis.String(object.folioId) : "",
      parcelId: isSet(object.parcelId) ? globalThis.String(object.parcelId) : "",
      registryId: isSet(object.registryId) ? globalThis.String(object.registryId) : "",
      folioNumber: isSet(object.folioNumber) ? globalThis.String(object.folioNumber) : "",
      landDescription: isSet(object.landDescription) ? globalThis.String(object.landDescription) : "",
      extent: isSet(object.extent) ? globalThis.String(object.extent) : "",
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
    };
  },

  toJSON(message: MsgCreateFolio): unknown {
    const obj: any = {};
    if (message.registrar !== "") {
      obj.registrar = message.registrar;
    }
    if (message.folioId !== "") {
      obj.folioId = message.folioId;
    }
    if (message.parcelId !== "") {
      obj.parcelId = message.parcelId;
    }
    if (message.registryId !== "") {
      obj.registryId = message.registryId;
    }
    if (message.folioNumber !== "") {
      obj.folioNumber = message.folioNumber;
    }
    if (message.landDescription !== "") {
      obj.landDescription = message.landDescription;
    }
    if (message.extent !== "") {
      obj.extent = message.extent;
    }
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgCreateFolio>, I>>(base?: I): MsgCreateFolio {
    return MsgCreateFolio.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCreateFolio>, I>>(object: I): MsgCreateFolio {
    const message = createBaseMsgCreateFolio();
    message.registrar = object.registrar ?? "";
    message.folioId = object.folioId ?? "";
    message.parcelId = object.parcelId ?? "";
    message.registryId = object.registryId ?? "";
    message.folioNumber = object.folioNumber ?? "";
    message.landDescription = object.landDescription ?? "";
    message.extent = object.extent ?? "";
    message.creator = object.creator ?? "";
    return message;
  },
};

function createBaseMsgCreateFolioResponse(): MsgCreateFolioResponse {
  return { status: "", code: 0, message: "", data: "", requestId: "", timestamp: "" };
}

export const MsgCreateFolioResponse: MessageFns<MsgCreateFolioResponse> = {
  encode(message: MsgCreateFolioResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.code !== 0) {
      writer.uint32(16).int32(message.code);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    if (message.data !== "") {
      writer.uint32(34).string(message.data);
    }
    if (message.requestId !== "") {
      writer.uint32(42).string(message.requestId);
    }
    if (message.timestamp !== "") {
      writer.uint32(50).string(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCreateFolioResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCreateFolioResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.code = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.data = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgCreateFolioResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      data: isSet(object.data) ? globalThis.String(object.data) : "",
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
    };
  },

  toJSON(message: MsgCreateFolioResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.data !== "") {
      obj.data = message.data;
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.timestamp !== "") {
      obj.timestamp = message.timestamp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgCreateFolioResponse>, I>>(base?: I): MsgCreateFolioResponse {
    return MsgCreateFolioResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCreateFolioResponse>, I>>(object: I): MsgCreateFolioResponse {
    const message = createBaseMsgCreateFolioResponse();
    message.status = object.status ?? "";
    message.code = object.code ?? 0;
    message.message = object.message ?? "";
    message.data = object.data ?? "";
    message.requestId = object.requestId ?? "";
    message.timestamp = object.timestamp ?? "";
    return message;
  },
};

function createBaseMsgRegisterDeedInFolio(): MsgRegisterDeedInFolio {
  return { registrarId: "", folioId: "", deedId: "", creator: "" };
}

export const MsgRegisterDeedInFolio: MessageFns<MsgRegisterDeedInFolio> = {
  encode(message: MsgRegisterDeedInFolio, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.registrarId !== "") {
      writer.uint32(10).string(message.registrarId);
    }
    if (message.folioId !== "") {
      writer.uint32(18).string(message.folioId);
    }
    if (message.deedId !== "") {
      writer.uint32(26).string(message.deedId);
    }
    if (message.creator !== "") {
      writer.uint32(42).string(message.creator);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRegisterDeedInFolio {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgRegisterDeedInFolio();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.registrarId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.folioId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.deedId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgRegisterDeedInFolio {
    return {
      registrarId: isSet(object.registrarId) ? globalThis.String(object.registrarId) : "",
      folioId: isSet(object.folioId) ? globalThis.String(object.folioId) : "",
      deedId: isSet(object.deedId) ? globalThis.String(object.deedId) : "",
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
    };
  },

  toJSON(message: MsgRegisterDeedInFolio): unknown {
    const obj: any = {};
    if (message.registrarId !== "") {
      obj.registrarId = message.registrarId;
    }
    if (message.folioId !== "") {
      obj.folioId = message.folioId;
    }
    if (message.deedId !== "") {
      obj.deedId = message.deedId;
    }
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRegisterDeedInFolio>, I>>(base?: I): MsgRegisterDeedInFolio {
    return MsgRegisterDeedInFolio.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRegisterDeedInFolio>, I>>(object: I): MsgRegisterDeedInFolio {
    const message = createBaseMsgRegisterDeedInFolio();
    message.registrarId = object.registrarId ?? "";
    message.folioId = object.folioId ?? "";
    message.deedId = object.deedId ?? "";
    message.creator = object.creator ?? "";
    return message;
  },
};

function createBaseMsgRegisterDeedInFolioResponse(): MsgRegisterDeedInFolioResponse {
  return { status: "", code: 0, message: "", data: "", requestId: "", timestamp: "" };
}

export const MsgRegisterDeedInFolioResponse: MessageFns<MsgRegisterDeedInFolioResponse> = {
  encode(message: MsgRegisterDeedInFolioResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.code !== 0) {
      writer.uint32(16).int32(message.code);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    if (message.data !== "") {
      writer.uint32(34).string(message.data);
    }
    if (message.requestId !== "") {
      writer.uint32(42).string(message.requestId);
    }
    if (message.timestamp !== "") {
      writer.uint32(50).string(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRegisterDeedInFolioResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgRegisterDeedInFolioResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.code = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.data = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgRegisterDeedInFolioResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      data: isSet(object.data) ? globalThis.String(object.data) : "",
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
    };
  },

  toJSON(message: MsgRegisterDeedInFolioResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.data !== "") {
      obj.data = message.data;
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.timestamp !== "") {
      obj.timestamp = message.timestamp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRegisterDeedInFolioResponse>, I>>(base?: I): MsgRegisterDeedInFolioResponse {
    return MsgRegisterDeedInFolioResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRegisterDeedInFolioResponse>, I>>(
    object: I,
  ): MsgRegisterDeedInFolioResponse {
    const message = createBaseMsgRegisterDeedInFolioResponse();
    message.status = object.status ?? "";
    message.code = object.code ?? 0;
    message.message = object.message ?? "";
    message.data = object.data ?? "";
    message.requestId = object.requestId ?? "";
    message.timestamp = object.timestamp ?? "";
    return message;
  },
};

/** Msg defines the Msg service. */
export interface Msg {
  /**
   * CreateFolio allows a Registry Officer to create a new folio record for a registered land parcel.
   * Each folio acts as the central ledger entry for property ownership, linking all associated deeds and documents.
   * Emits a `folio_created` event on success.
   */
  CreateFolio(request: MsgCreateFolio): Promise<MsgCreateFolioResponse>;
  /**
   * RegisterDeedInFolio links a newly issued deed to its corresponding folio record.
   * This updates the folio’s deed history and sets the current active deed reference.
   * Typically triggered automatically after `deed_issued` events.
   */
  RegisterDeedInFolio(request: MsgRegisterDeedInFolio): Promise<MsgRegisterDeedInFolioResponse>;
  /**
   * SubmitNotarySignature allows a Notary to digitally sign a folio or related deed entry.
   * This ensures notarization of the transaction and adds legal verification to the folio record.
   */
  SubmitNotarySignature(request: MsgSubmitNotarySignature): Promise<MsgSubmitNotarySignatureResponse>;
  /**
   * RequestFolio allows an external user (e.g., landowner or authorized agent) to request access to a folio extract.
   * The request is stored on-chain and awaits review by the Registry Office for approval or rejection.
   */
  RequestFolio(request: MsgRequestFolio): Promise<MsgRequestFolioResponse>;
  /**
   * ApproveFolioRequest allows a Registry Officer to review and approve a folio extract request submitted by a user.
   * Once approved, the requester is granted permission to view or retrieve the folio data.
   */
  ApproveFolioRequest(request: MsgApproveFolioRequest): Promise<MsgApproveFolioRequestResponse>;
}

export const MsgServiceName = "elandnode.folio.v1.Msg";
export class MsgClientImpl implements Msg {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || MsgServiceName;
    this.rpc = rpc;
    this.CreateFolio = this.CreateFolio.bind(this);
    this.RegisterDeedInFolio = this.RegisterDeedInFolio.bind(this);
    this.SubmitNotarySignature = this.SubmitNotarySignature.bind(this);
    this.RequestFolio = this.RequestFolio.bind(this);
    this.ApproveFolioRequest = this.ApproveFolioRequest.bind(this);
  }
  CreateFolio(request: MsgCreateFolio): Promise<MsgCreateFolioResponse> {
    const data = MsgCreateFolio.encode(request).finish();
    const promise = this.rpc.request(this.service, "CreateFolio", data);
    return promise.then((data) => MsgCreateFolioResponse.decode(new BinaryReader(data)));
  }

  RegisterDeedInFolio(request: MsgRegisterDeedInFolio): Promise<MsgRegisterDeedInFolioResponse> {
    const data = MsgRegisterDeedInFolio.encode(request).finish();
    const promise = this.rpc.request(this.service, "RegisterDeedInFolio", data);
    return promise.then((data) => MsgRegisterDeedInFolioResponse.decode(new BinaryReader(data)));
  }

  SubmitNotarySignature(request: MsgSubmitNotarySignature): Promise<MsgSubmitNotarySignatureResponse> {
    const data = MsgSubmitNotarySignature.encode(request).finish();
    const promise = this.rpc.request(this.service, "SubmitNotarySignature", data);
    return promise.then((data) => MsgSubmitNotarySignatureResponse.decode(new BinaryReader(data)));
  }

  RequestFolio(request: MsgRequestFolio): Promise<MsgRequestFolioResponse> {
    const data = MsgRequestFolio.encode(request).finish();
    const promise = this.rpc.request(this.service, "RequestFolio", data);
    return promise.then((data) => MsgRequestFolioResponse.decode(new BinaryReader(data)));
  }

  ApproveFolioRequest(request: MsgApproveFolioRequest): Promise<MsgApproveFolioRequestResponse> {
    const data = MsgApproveFolioRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "ApproveFolioRequest", data);
    return promise.then((data) => MsgApproveFolioRequestResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
